// song-data.js
// generated: 16-6-26
// version file: 01

const songs = [
  {
    title: "Ain’t no sunshine",
    artist: "Bill Withers",
    url: "lyrics/song.html?id=aintnosunshine",
    year: 1971,
    bpm: 76,
    gender: "Male",
    genre: "Soul",
    vibe: "Classic",
    energy: "Medium Low",
    energyPeak: "Wave",
    crowdFunction: "Shoutback",
    vocalDemand: "Extreme",
    setPosition: "Peak",
    reliabilityScore: "Safe",
    venueFit: "Club",
    setFrequency: "normal",
    hostKaraokePage: "39",
    livePage: "113",
    hasLyrics: true
  },
  {
    title: "All along the watchtower",
    artist: "Jimi Hendrix",
    url: "lyrics/song.html?id=allalongthewatchtower",
    year: 1967,
    bpm: 113,
    gender: "Male",
    genre: "Rock",
    vibe: "Dark",
    energy: "High",
    energyPeak: "Building",
    crowdFunction: "Listening",
    vocalDemand: "Hard",
    setPosition: "Mid Set",
    reliabilityScore: "Risky",
    venueFit: "Outdoor",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: false
  },
  {
    title: "All summer long",
    artist: "Kid Rock",
    url: "lyrics/song.html?id=allsummerlong",
    year: 2007,
    bpm: 101,
    gender: "Male",
    genre: "Rock",
    vibe: "Anthem",
    energy: "Very High",
    energyPeak: "Wave",
    crowdFunction: "Dance",
    vocalDemand: "Extreme",
    setPosition: "Opening",
    reliabilityScore: "Safe",
    venueFit: "Small Acoustic",
    setFrequency: "rare",
    hostKaraokePage: "54",
    livePage: "156",
    hasLyrics: true
  },
  {
    title: "All the small things",
    artist: "Blink 182",
    url: "lyrics/song.html?id=allthesmallthings",
    year: 1999,
    bpm: 149,
    gender: "Male",
    genre: "Rock",
    vibe: "Party",
    energy: "High",
    energyPeak: "Building",
    crowdFunction: "Dance",
    vocalDemand: "Easy",
    setPosition: "Mid Set",
    reliabilityScore: "Risky",
    venueFit: "Small Acoustic",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Allting Kommer Att Bli Bra",
    artist: "Johan Airjoki",
    url: "lyrics/song.html?id=alltingkommerattblibra",
    year: 2017,
    bpm: 60,
    gender: "Male",
    genre: "Rock",
    vibe: "Party",
    energy: "Low",
    energyPeak: "Drop",
    crowdFunction: "Shoutback",
    vocalDemand: "Medium",
    setPosition: "Closer",
    reliabilityScore: "Safe",
    venueFit: "Arena style",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Angels",
    artist: "Robbie Williams",
    url: "lyrics/song.html?id=angels",
    year: 1997,
    bpm: 75,
    gender: "Male",
    genre: "Pop",
    vibe: "Classic",
    energy: "Very High",
    energyPeak: "Wave",
    crowdFunction: "Emotional",
    vocalDemand: "Easy",
    setPosition: "Opening",
    reliabilityScore: "Safe",
    venueFit: "Outdoor",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Angie",
    artist: "Rolling Stones",
    url: "lyrics/song.html?id=angie",
    year: 1973,
    bpm: 69,
    gender: "Male",
    genre: "Rock",
    vibe: "Romantic",
    energy: "Low",
    energyPeak: "Steady",
    crowdFunction: "Listening",
    vocalDemand: "Easy",
    setPosition: "Closer",
    reliabilityScore: "Safe",
    venueFit: "Pub",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: false
  },
  {
    title: "Another brick in the wall pt. 2",
    artist: "Pink Floyd",
    url: "lyrics/song.html?id=anotherbrickinthewallpt2",
    year: 1979,
    bpm: 103,
    gender: "Male",
    genre: "Rock",
    vibe: "Anthem",
    energy: "Low",
    energyPeak: "Building",
    crowdFunction: "Dance",
    vocalDemand: "Medium",
    setPosition: "Closer",
    reliabilityScore: "Safe",
    venueFit: "Outdoor",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Another one bites the dust",
    artist: "Queen",
    url: "lyrics/song.html?id=anotheronebitesthedust",
    year: 1980,
    bpm: 110,
    gender: "Male",
    genre: "Rock",
    vibe: "Party",
    energy: "High",
    energyPeak: "Steady",
    crowdFunction: "Dance",
    vocalDemand: "Medium",
    setPosition: "Mid Set",
    reliabilityScore: "Safe",
    venueFit: "Club",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Bad Moon Rising",
    artist: "CCR",
    url: "lyrics/song.html?id=badmoonrising",
    year: 1969,
    bpm: 177,
    gender: "Male",
    genre: "Rock",
    vibe: "Chill",
    energy: "High",
    energyPeak: "Drop",
    crowdFunction: "Singalong",
    vocalDemand: "Extreme",
    setPosition: "Opening",
    reliabilityScore: "Safe",
    venueFit: "Club",
    setFrequency: "overused",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Bad Romance",
    artist: "Lady Gaga",
    url: "lyrics/song.html?id=badromance",
    year: 2009,
    bpm: 119,
    gender: "Female",
    genre: "Pop",
    vibe: "Party",
    energy: "Very High",
    energyPeak: "Drop",
    crowdFunction: "Dance",
    vocalDemand: "Hard",
    setPosition: "Peak",
    reliabilityScore: "Safe",
    venueFit: "Club",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Basket Case",
    artist: "Green Day",
    url: "lyrics/song.html?id=basketcase",
    year: 1994,
    bpm: 170,
    gender: "Male",
    genre: "Rock",
    vibe: "Classic",
    energy: "Very High",
    energyPeak: "Building",
    crowdFunction: "Singalong",
    vocalDemand: "Easy",
    setPosition: "Cooldown",
    reliabilityScore: "Risky",
    venueFit: "Outdoor",
    setFrequency: "overused",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Beds are Burning",
    artist: "Midnight Oil",
    url: "lyrics/song.html?id=bedsareburning",
    year: 1987,
    bpm: 119,
    gender: "Male",
    genre: "Rock",
    vibe: "Romantic",
    energy: "Medium",
    energyPeak: "Drop",
    crowdFunction: "Dance",
    vocalDemand: "Medium",
    setPosition: "Build",
    reliabilityScore: "Safe",
    venueFit: "Small Acoustic",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: false
  },
  {
    title: "Behind blue eyes",
    artist: "Who, The",
    url: "lyrics/song.html?id=behindblueeyes",
    year: 1971,
    bpm: 66/132,
    gender: "Male",
    genre: "Rock",
    vibe: "Anthem",
    energy: "Very High",
    energyPeak: "Steady",
    crowdFunction: "Background",
    vocalDemand: "Extreme",
    setPosition: "Build",
    reliabilityScore: "Risky",
    venueFit: "Outdoor",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Bella Ciao",
    artist: "Italian Traditional",
    url: "lyrics/song.html?id=bellaciao",
    year: 1953,
    bpm: 134,
    gender: "Male",
    genre: "Rock",
    vibe: "Party",
    energy: "Medium",
    energyPeak: "Wave",
    crowdFunction: "Background",
    vocalDemand: "Extreme",
    setPosition: "Mid Set",
    reliabilityScore: "Risky",
    venueFit: "Flexible",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Big Me",
    artist: "Foo Fighters",
    url: "lyrics/song.html?id=bigme",
    year: 1996,
    bpm: 130,
    gender: "Male",
    genre: "Rock",
    vibe: "Romantic",
    energy: "Low",
    energyPeak: "Building",
    crowdFunction: "Shoutback",
    vocalDemand: "Hard",
    setPosition: "Closer",
    reliabilityScore: "Risky",
    venueFit: "Arena style",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Bittersweet Symphony",
    artist: "Verve, The",
    url: "lyrics/song.html?id=bittersweetsymphony",
    year: 1997,
    bpm: 85,
    gender: "Male",
    genre: "Rock",
    vibe: "Drama",
    energy: "Very Low",
    energyPeak: "Steady",
    crowdFunction: "Dance",
    vocalDemand: "Easy",
    setPosition: "Mid Set",
    reliabilityScore: "Moderate",
    venueFit: "Arena style",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: false
  },
  {
    title: "Bohemian like you",
    artist: "Dandy Warhols",
    url: "lyrics/song.html?id=bohemianlikeyou",
    year: 2000,
    bpm: 131,
    gender: "Male",
    genre: "Rock",
    vibe: "Party",
    energy: "Low",
    energyPeak: "Building",
    crowdFunction: "Background",
    vocalDemand: "Easy",
    setPosition: "Cooldown",
    reliabilityScore: "Moderate",
    venueFit: "Flexible",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: false
  },
  {
    title: "Born to be wild",
    artist: "Steppenwolf",
    url: "lyrics/song.html?id=borntobewild",
    year: 1968,
    bpm: 144,
    gender: "Male",
    genre: "Rock",
    vibe: "Party",
    energy: "High",
    energyPeak: "Building",
    crowdFunction: "Emotional",
    vocalDemand: "Medium",
    setPosition: "Peak",
    reliabilityScore: "Risky",
    venueFit: "Club",
    setFrequency: "overused",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Boulevard of Broken Dreams",
    artist: "Green Day",
    url: "lyrics/song.html?id=boulevardofbrokendreams",
    year: 2004,
    bpm: 83,
    gender: "Male",
    genre: "Rock",
    vibe: "Party",
    energy: "High",
    energyPeak: "Drop",
    crowdFunction: "Listening",
    vocalDemand: "Extreme",
    setPosition: "Mid Set",
    reliabilityScore: "Moderate",
    venueFit: "Outdoor",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Breakfast at Tiffany's",
    artist: "Deep Blue Something",
    url: "lyrics/song.html?id=breakfastattiffanys",
    year: 1995,
    bpm: 102,
    gender: "Male",
    genre: "Rock",
    vibe: "Romantic",
    energy: "Medium Low",
    energyPeak: "Wave",
    crowdFunction: "Shoutback",
    vocalDemand: "Medium",
    setPosition: "Cooldown",
    reliabilityScore: "Safe",
    venueFit: "Arena style",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Californication",
    artist: "Red Hot Chili Peppers",
    url: "lyrics/song.html?id=californication",
    year: 1999,
    bpm: 91,
    gender: "Male",
    genre: "Rock",
    vibe: "Dark",
    energy: "High",
    energyPeak: "Wave",
    crowdFunction: "Background",
    vocalDemand: "Medium",
    setPosition: "Cooldown",
    reliabilityScore: "Risky",
    venueFit: "Arena style",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Call Me The Breeze",
    artist: "Lynyrd Skynyrd",
    url: "lyrics/song.html?id=callmethebreeze",
    year: 1971,
    bpm: 94,
    gender: "Male",
    genre: "Rock",
    vibe: "Chill",
    energy: "Medium High",
    energyPeak: "Steady",
    crowdFunction: "Singalong",
    vocalDemand: "Easy",
    setPosition: "Opening",
    reliabilityScore: "Moderate",
    venueFit: "Pub",
    setFrequency: "overused",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Can't get enough",
    artist: "Bad Company",
    url: "lyrics/song.html?id=cantgetenough",
    year: 1974,
    bpm: 129,
    gender: "Male",
    genre: "Rock",
    vibe: "Party",
    energy: "High",
    energyPeak: "Steady",
    crowdFunction: "Dance",
    vocalDemand: "Medium",
    setPosition: "Build",
    reliabilityScore: "Safe",
    venueFit: "Club",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Can't take my eyes off you",
    artist: "Frankie Valli / Muse",
    url: "lyrics/song.html?id=canttakemyeyesoffyou",
    year: 1967,
    bpm: 124,
    gender: "Male",
    genre: "Rock",
    vibe: "Anthem",
    energy: "Medium High",
    energyPeak: "Building",
    crowdFunction: "Dance",
    vocalDemand: "Medium",
    setPosition: "Build",
    reliabilityScore: "Moderate",
    venueFit: "Pub",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Changes",
    artist: "Black Sabbath",
    url: "lyrics/song.html?id=changes",
    year: 1972,
    bpm: 81,
    gender: "Male",
    genre: "Metal",
    vibe: "Classic",
    energy: "Medium",
    energyPeak: "Building",
    crowdFunction: "Listening",
    vocalDemand: "Medium",
    setPosition: "Peak",
    reliabilityScore: "Moderate",
    venueFit: "Small Acoustic",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Caroline",
    artist: "Status Quo",
    url: "lyrics/song.html?id=caroline",
    year: 1973,
    bpm: 153,
    gender: "Male",
    genre: "Classic",
    vibe: "Classic",
    energy: "Medium",
    energyPeak: "Building",
    crowdFunction: "Listening",
    vocalDemand: "Medium",
    setPosition: "Peak",
    reliabilityScore: "Moderate",
    venueFit: "Small Acoustic",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Chasing Cars",
    artist: "Snow Patrol",
    url: "lyrics/song.html?id=chasingcars",
    year: 2006,
    bpm: 104,
    gender: "Male",
    genre: "Indie",
    vibe: "Chill",
    energy: "Low",
    energyPeak: "Steady",
    crowdFunction: "Emotional",
    vocalDemand: "Easy",
    setPosition: "Peak",
    reliabilityScore: "Safe",
    venueFit: "Club",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Clocks",
    artist: "Coldplay",
    url: "lyrics/song.html?id=clocks",
    year: 2002,
    bpm: 131,
    gender: "Male",
    genre: "Pop",
    vibe: "Romantic",
    energy: "High",
    energyPeak: "Building",
    crowdFunction: "Listening",
    vocalDemand: "Medium",
    setPosition: "Build",
    reliabilityScore: "Risky",
    venueFit: "Arena style",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Cocaine",
    artist: "Eric Clapton",
    url: "lyrics/song.html?id=cocaine",
    year: 1976,
    bpm: 105,
    gender: "Male",
    genre: "Blues",
    vibe: "Rock",
    energy: "High",
    energyPeak: "Wave",
    crowdFunction: "Shoutback",
    vocalDemand: "Medium",
    setPosition: "Cooldown",
    reliabilityScore: "Safe",
    venueFit: "Outdoor",
    setFrequency: "overused",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Come As you are",
    artist: "Nirvana",
    url: "lyrics/song.html?id=comeasyouare",
    year: 1991,
    bpm: 120,
    gender: "Male",
    genre: "Rock",
    vibe: "Classic",
    energy: "Very Low",
    energyPeak: "Steady",
    crowdFunction: "Shoutback",
    vocalDemand: "Medium",
    setPosition: "Closer",
    reliabilityScore: "Moderate",
    venueFit: "Small Acoustic",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Come Together",
    artist: "Beatles, The",
    url: "lyrics/song.html?id=cometogether",
    year: 1969,
    bpm: 82,
    gender: "Male",
    genre: "Pop",
    vibe: "Dark",
    energy: "Medium High",
    energyPeak: "Drop",
    crowdFunction: "Singalong",
    vocalDemand: "Hard",
    setPosition: "Mid Set",
    reliabilityScore: "Moderate",
    venueFit: "Flexible",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Could you be loved",
    artist: "Bob Marley",
    url: "lyrics/song.html?id=couldyoubeloved",
    year: 1980,
    bpm: 102,
    gender: "Male",
    genre: "Reggae",
    vibe: "Rock",
    energy: "Medium Low",
    energyPeak: "Drop",
    crowdFunction: "Emotional",
    vocalDemand: "Hard",
    setPosition: "Cooldown",
    reliabilityScore: "Risky",
    venueFit: "Arena style",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Crazy little thing called love",
    artist: "Queen",
    url: "lyrics/song.html?id=crazylittlethingcalledlove",
    year: 1979,
    bpm: 154,
    gender: "Male",
    genre: "Rock",
    vibe: "Party",
    energy: "Medium High",
    energyPeak: "Steady",
    crowdFunction: "Dance",
    vocalDemand: "Medium",
    setPosition: "Build",
    reliabilityScore: "Safe",
    venueFit: "Pub",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: false
  },
  {
    title: "Creep",
    artist: "Radiohead",
    url: "lyrics/song.html?id=creep",
    year: 1992,
    bpm: 89,
    gender: "Male",
    genre: "Indie",
    vibe: "Romantic",
    energy: "Very Low",
    energyPeak: "Drop",
    crowdFunction: "Singalong",
    vocalDemand: "Medium",
    setPosition: "Mid Set",
    reliabilityScore: "Safe",
    venueFit: "Outdoor",
    setFrequency: "overused",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Dakota",
    artist: "Stereophonics",
    url: "lyrics/song.html?id=dakota",
    year: 2005,
    bpm: 147,
    gender: "Male",
    genre: "Rock",
    vibe: "Party",
    energy: "High",
    energyPeak: "Steady",
    crowdFunction: "Dance",
    vocalDemand: "Extreme",
    setPosition: "Opening",
    reliabilityScore: "Risky",
    venueFit: "Arena style",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Dani California",
    artist: "Red Hot Chili Peppers",
    url: "lyrics/song.html?id=danicalifornia",
    year: 2006,
    bpm: 96,
    gender: "Male",
    genre: "Rock",
    vibe: "Dark",
    energy: "Medium High",
    energyPeak: "Steady",
    crowdFunction: "Singalong",
    vocalDemand: "Hard",
    setPosition: "Closer",
    reliabilityScore: "Safe",
    venueFit: "Pub",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: false
  },
  {
    title: "Do I wanna know",
    artist: "Arctic Monkeys",
    url: "lyrics/song.html?id=doiwannaknow",
    year: 2013,
    bpm: 85,
    gender: "Male",
    genre: "Indie",
    vibe: "Rock",
    energy: "Medium",
    energyPeak: "Drop",
    crowdFunction: "Dance",
    vocalDemand: "Easy",
    setPosition: "Cooldown",
    reliabilityScore: "Risky",
    venueFit: "Arena style",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: false
  },
  {
    title: "Don’t look back in anger",
    artist: "Oasis",
    url: "lyrics/song.html?id=dontlookbackinanger",
    year: 1996,
    bpm: 80,
    gender: "Male",
    genre: "Rock",
    vibe: "Romantic",
    energy: "High",
    energyPeak: "Drop",
    crowdFunction: "Shoutback",
    vocalDemand: "Easy",
    setPosition: "Cooldown",
    reliabilityScore: "Risky",
    venueFit: "Outdoor",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Don't stop me now",
    artist: "Queen",
    url: "lyrics/song.html?id=dontstopmenow",
    year: 1979,
    bpm: 157,
    gender: "Male",
    genre: "Rock",
    vibe: "Anthem",
    energy: "Very High",
    energyPeak: "Building",
    crowdFunction: "Singalong",
    vocalDemand: "Hard",
    setPosition: "Closer",
    reliabilityScore: "Safe",
    venueFit: "Arena style",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Down under",
    artist: "Men at Work",
    url: "lyrics/song.html?id=downunder",
    year: 1981,
    bpm: 107,
    gender: "Male",
    genre: "Pop",
    vibe: "Party",
    energy: "Medium High",
    energyPeak: "Steady",
    crowdFunction: "Singalong",
    vocalDemand: "Medium",
    setPosition: "Mid Set",
    reliabilityScore: "Safe",
    venueFit: "Pub",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Dreams",
    artist: "Fleetwood Mac",
    url: "lyrics/song.html?id=dreams",
    year: 1977,
    bpm: 120,
    gender: "Female",
    genre: "Rock",
    vibe: "Romantic",
    energy: "Medium",
    energyPeak: "Wave",
    crowdFunction: "Listening",
    vocalDemand: "Extreme",
    setPosition: "Peak",
    reliabilityScore: "Moderate",
    venueFit: "Outdoor",
    setFrequency: "overused",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Drive",
    artist: "Incubus",
    url: "lyrics/song.html?id=drive",
    year: 1999,
    bpm: 90,
    gender: "Male",
    genre: "Rock",
    vibe: "Chill",
    energy: "High",
    energyPeak: "Wave",
    crowdFunction: "Background",
    vocalDemand: "Extreme",
    setPosition: "Peak",
    reliabilityScore: "Moderate",
    venueFit: "Outdoor",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Drops of Jupiter",
    artist: "Train",
    url: "lyrics/song.html?id=dropsofjupiter",
    year: 2001,
    bpm: 79,
    gender: "Male",
    genre: "Rock",
    vibe: "Drama",
    energy: "Very High",
    energyPeak: "Drop",
    crowdFunction: "Background",
    vocalDemand: "Easy",
    setPosition: "Cooldown",
    reliabilityScore: "Risky",
    venueFit: "Pub",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Every breath you take",
    artist: "Police, The",
    url: "lyrics/song.html?id=everybreathyoutake",
    year: 1983,
    bpm: 117,
    gender: "Male",
    genre: "Rock",
    vibe: "Romantic",
    energy: "High",
    energyPeak: "Wave",
    crowdFunction: "Background",
    vocalDemand: "Easy",
    setPosition: "Build",
    reliabilityScore: "Risky",
    venueFit: "Small Acoustic",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Every rose has its thorn",
    artist: "Poison",
    url: "lyrics/song.html?id=everyrosehasitsthorn",
    year: 1988,
    bpm: 70,
    gender: "Male",
    genre: "Rock",
    vibe: "Rock",
    energy: "High",
    energyPeak: "Steady",
    crowdFunction: "Shoutback",
    vocalDemand: "Medium",
    setPosition: "Build",
    reliabilityScore: "Safe",
    venueFit: "Arena style",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: false
  },
  {
    title: "Fat bottomed girls",
    artist: "Queen",
    url: "lyrics/song.html?id=fatbottomedgirls",
    year: 1978,
    bpm: 89,
    gender: "Male",
    genre: "Rock",
    vibe: "Party",
    energy: "High",
    energyPeak: "Wave",
    crowdFunction: "Singalong",
    vocalDemand: "Medium",
    setPosition: "Peak",
    reliabilityScore: "Safe",
    venueFit: "Arena style",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Feel like making love",
    artist: "Bad Company",
    url: "lyrics/song.html?id=feellikemakinglove",
    year: 1975,
    bpm: 82,
    gender: "Male",
    genre: "Rock",
    vibe: "Drama",
    energy: "Medium Low",
    energyPeak: "Steady",
    crowdFunction: "Shoutback",
    vocalDemand: "Hard",
    setPosition: "Peak",
    reliabilityScore: "Moderate",
    venueFit: "Arena style",
    setFrequency: "overused",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Flowers",
    artist: "Miley Cyrus",
    url: "lyrics/song.html?id=flowers",
    year: 2023,
    bpm: 118,
    gender: "Female",
    genre: "Pop",
    vibe: "Party",
    energy: "Medium High",
    energyPeak: "Steady",
    crowdFunction: "Singalong",
    vocalDemand: "Easy",
    setPosition: "Build",
    reliabilityScore: "Safe",
    venueFit: "Club",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Free Bird",
    artist: "Lynyrd Skynyrd",
    url: "lyrics/song.html?id=freebird",
    year: 1973,
    bpm: 117/154,
    gender: "Male",
    genre: "Rock",
    vibe: "Anthem",
    energy: "High",
    energyPeak: "Drop",
    crowdFunction: "Listening",
    vocalDemand: "Medium",
    setPosition: "Closer",
    reliabilityScore: "Moderate",
    venueFit: "Club",
    setFrequency: "overused",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Friday I’m in love",
    artist: "Cure, The",
    url: "lyrics/song.html?id=fridayiminlove",
    year: 1992,
    bpm: 132,
    gender: "Male",
    genre: "Rock",
    vibe: "Rock",
    energy: "Very High",
    energyPeak: "Drop",
    crowdFunction: "Emotional",
    vocalDemand: "Hard",
    setPosition: "Closer",
    reliabilityScore: "Moderate",
    venueFit: "Pub",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Gimme all your lovin’",
    artist: "ZZ Top",
    url: "lyrics/song.html?id=gimmeallyourlovin",
    year: 1983,
    bpm: 120,
    gender: "Male",
    genre: "Blues",
    vibe: "Romantic",
    energy: "Medium Low",
    energyPeak: "Building",
    crowdFunction: "Listening",
    vocalDemand: "Hard",
    setPosition: "Mid Set",
    reliabilityScore: "Risky",
    venueFit: "Arena style",
    setFrequency: "overused",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Go with the flow",
    artist: "Queens of the stone age",
    url: "lyrics/song.html?id=gowiththeflow",
    year: 2002,
    bpm: 146,
    gender: "Male",
    genre: "Rock",
    vibe: "Drama",
    energy: "Very High",
    energyPeak: "Steady",
    crowdFunction: "Emotional",
    vocalDemand: "Medium",
    setPosition: "Closer",
    reliabilityScore: "Risky",
    venueFit: "Club",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: false
  },
  {
    title: "Good Riddance",
    artist: "Green Day",
    url: "lyrics/song.html?id=goodriddance",
    year: 1997,
    bpm: 95,
    gender: "Male",
    genre: "Rock",
    vibe: "Party",
    energy: "Medium",
    energyPeak: "Steady",
    crowdFunction: "Listening",
    vocalDemand: "Medium",
    setPosition: "Cooldown",
    reliabilityScore: "Risky",
    venueFit: "Arena style",
    setFrequency: "overused",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Hard to handle",
    artist: "Black Crowes",
    url: "lyrics/song.html?id=hardtohandle",
    year: 1968,
    bpm: 104,
    gender: "Male",
    genre: "Rock",
    vibe: "Classic",
    energy: "Very High",
    energyPeak: "Steady",
    crowdFunction: "Listening",
    vocalDemand: "Easy",
    setPosition: "Peak",
    reliabilityScore: "Safe",
    venueFit: "Pub",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: false
  },
  {
    title: "Have you ever seen the rain",
    artist: "CCR",
    url: "lyrics/song.html?id=haveyoueverseentherain",
    year: 1971,
    bpm: 117,
    gender: "Male",
    genre: "Rock",
    vibe: "Rock",
    energy: "Medium",
    energyPeak: "Wave",
    crowdFunction: "Background",
    vocalDemand: "Medium",
    setPosition: "Peak",
    reliabilityScore: "Safe",
    venueFit: "Small Acoustic",
    setFrequency: "overused",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Here without you",
    artist: "Three Doors Down",
    url: "lyrics/song.html?id=herewithoutyou",
    year: 2002,
    bpm: 72,
    gender: "Male",
    genre: "Rock",
    vibe: "Romantic",
    energy: "Medium",
    energyPeak: "Building",
    crowdFunction: "Emotional",
    vocalDemand: "Medium",
    setPosition: "Cooldown",
    reliabilityScore: "Safe",
    venueFit: "Flexible",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Hey Jude",
    artist: "Beatles, The",
    url: "lyrics/song.html?id=heyjude",
    year: 1968,
    bpm: 74,
    gender: "Male",
    genre: "Pop",
    vibe: "Rock",
    energy: "High",
    energyPeak: "Drop",
    crowdFunction: "Emotional",
    vocalDemand: "Easy",
    setPosition: "Cooldown",
    reliabilityScore: "Moderate",
    venueFit: "Small Acoustic",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Highway to Hell",
    artist: "ACDC",
    url: "lyrics/song.html?id=highwaytohell",
    year: 1979,
    bpm: 116,
    gender: "Male",
    genre: "Metal",
    vibe: "Classic",
    energy: "High",
    energyPeak: "Wave",
    crowdFunction: "Dance",
    vocalDemand: "Easy",
    setPosition: "Closer",
    reliabilityScore: "Moderate",
    venueFit: "Club",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Home Sweet Home",
    artist: "Motley Crue",
    url: "lyrics/song.html?id=homesweethome",
    year: 1985,
    bpm: 75,
    gender: "Male",
    genre: "Rock",
    vibe: "Anthem",
    energy: "High",
    energyPeak: "Wave",
    crowdFunction: "Emotional",
    vocalDemand: "Easy",
    setPosition: "Opening",
    reliabilityScore: "Safe",
    venueFit: "Pub",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Hotel California",
    artist: "Eagles, The",
    url: "lyrics/song.html?id=hotelcalifornia",
    year: 1976,
    bpm: 74,
    gender: "Male",
    genre: "Rock",
    vibe: "Chill",
    energy: "Medium High",
    energyPeak: "Steady",
    crowdFunction: "Shoutback",
    vocalDemand: "Extreme",
    setPosition: "Mid Set",
    reliabilityScore: "Safe",
    venueFit: "Small Acoustic",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "House of the rising sun",
    artist: "Animals, The",
    url: "lyrics/song.html?id=houseoftherisingsun",
    year: 1964,
    bpm: 78,
    gender: "Male",
    genre: "Rock",
    vibe: "Rock",
    energy: "Low",
    energyPeak: "Drop",
    crowdFunction: "Dance",
    vocalDemand: "Extreme",
    setPosition: "Build",
    reliabilityScore: "Risky",
    venueFit: "Club",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "How you remind me",
    artist: "Nickelback",
    url: "lyrics/song.html?id=howyouremindme",
    year: 2001,
    bpm: 86,
    gender: "Male",
    genre: "Rock",
    vibe: "Rock",
    energy: "Very Low",
    energyPeak: "Steady",
    crowdFunction: "Singalong",
    vocalDemand: "Hard",
    setPosition: "Opening",
    reliabilityScore: "Safe",
    venueFit: "Outdoor",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "I Don't Want to Talk About It",
    artist: "Rod Stewart",
    url: "lyrics/song.html?id=idontwanttotalkaboutit",
    year: 1975,
    bpm: 67,
    gender: "Male",
    genre: "Rock",
    vibe: "Rock",
    energy: "Very Low",
    energyPeak: "Steady",
    crowdFunction: "Singalong",
    vocalDemand: "Hard",
    setPosition: "Opening",
    reliabilityScore: "Safe",
    venueFit: "Outdoor",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "I see fire",
    artist: "Ed Sheeran",
    url: "lyrics/song.html?id=iseefire",
    year: 2013,
    bpm: 76,
    gender: "Male",
    genre: "Rock",
    vibe: "Classic",
    energy: "High",
    energyPeak: "Wave",
    crowdFunction: "Listening",
    vocalDemand: "Easy",
    setPosition: "Closer",
    reliabilityScore: "Safe",
    venueFit: "Club",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "I want to break free",
    artist: "Queen",
    url: "lyrics/song.html?id=iwanttobreakfree",
    year: 1984,
    bpm: 109,
    gender: "Male",
    genre: "Pop",
    vibe: "Anthem",
    energy: "High",
    energyPeak: "Building",
    crowdFunction: "Singalong",
    vocalDemand: "Medium",
    setPosition: "Peak",
    reliabilityScore: "Safe",
    venueFit: "Arena style",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: false
  },
  {
    title: "I will survive",
    artist: "Gloria Gaynor",
    url: "lyrics/song.html?id=iwillsurvive",
    year: 1978,
    bpm: 94,
    gender: "Female",
    genre: "Soul",
    vibe: "Chill",
    energy: "Medium High",
    energyPeak: "Building",
    crowdFunction: "Shoutback",
    vocalDemand: "Hard",
    setPosition: "Mid Set",
    reliabilityScore: "Moderate",
    venueFit: "Small Acoustic",
    setFrequency: "overused",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Imagine",
    artist: "John Lennon",
    url: "lyrics/song.html?id=imagine",
    year: 1971,
    bpm: 75,
    gender: "Male",
    genre: "Rock",
    vibe: "Dark",
    energy: "High",
    energyPeak: "Drop",
    crowdFunction: "Dance",
    vocalDemand: "Medium",
    setPosition: "Build",
    reliabilityScore: "Safe",
    venueFit: "Club",
    setFrequency: "overused",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "In the summertime",
    artist: "Mungo Jerry",
    url: "lyrics/song.html?id=inthesummertime",
    year: 1970,
    bpm: 83,
    gender: "Male",
    genre: "Rock",
    vibe: "Chill",
    energy: "Very Low",
    energyPeak: "Steady",
    crowdFunction: "Listening",
    vocalDemand: "Easy",
    setPosition: "Peak",
    reliabilityScore: "Safe",
    venueFit: "Small Acoustic",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Ironic",
    artist: "Alanis Morissette",
    url: "lyrics/song.html?id=ironic",
    year: 1995,
    bpm: 85,
    gender: "Female",
    genre: "Rock",
    vibe: "Drama",
    energy: "Medium",
    energyPeak: "Wave",
    crowdFunction: "Listening",
    vocalDemand: "Medium",
    setPosition: "Mid Set",
    reliabilityScore: "Safe",
    venueFit: "Flexible",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "It’s my life",
    artist: "Bon Jovi",
    url: "lyrics/song.html?id=itsmylife",
    year: 2000,
    bpm: 120,
    gender: "Male",
    genre: "Rock",
    vibe: "Romantic",
    energy: "Medium",
    energyPeak: "Drop",
    crowdFunction: "Listening",
    vocalDemand: "Medium",
    setPosition: "Opening",
    reliabilityScore: "Moderate",
    venueFit: "Small Acoustic",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Johnny B Goode",
    artist: "Chuck Berry",
    url: "lyrics/song.html?id=johnnybgoode",
    year: 1958,
    bpm: 149,
    gender: "Male",
    genre: "Rock",
    vibe: "Drama",
    energy: "Medium",
    energyPeak: "Building",
    crowdFunction: "Emotional",
    vocalDemand: "Medium",
    setPosition: "Build",
    reliabilityScore: "Risky",
    venueFit: "Outdoor",
    setFrequency: "overused",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Jolene",
    artist: "Dolly Parton",
    url: "lyrics/song.html?id=jolene",
    year: 1973,
    bpm: 112,
    gender: "Female",
    genre: "Country",
    vibe: "Drama",
    energy: "Medium",
    energyPeak: "Building",
    crowdFunction: "Listening",
    vocalDemand: "Medium",
    setPosition: "Mid Set",
    reliabilityScore: "Safe",
    venueFit: "Pub",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Knockin’ on Heaven’s Door",
    artist: "Bob Dylan/Guns N Roses",
    url: "lyrics/song.html?id=knockinonheavensdoor",
    year: 1973,
    bpm: 66,
    gender: "Male",
    genre: "Rock",
    vibe: "Classic",
    energy: "High",
    energyPeak: "Wave",
    crowdFunction: "Singalong",
    vocalDemand: "Easy",
    setPosition: "Cooldown",
    reliabilityScore: "Safe",
    venueFit: "Pub",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Kryptonite",
    artist: "Three Doors Down",
    url: "lyrics/song.html?id=kryptonite",
    year: 2000,
    bpm: 95,
    gender: "Male",
    genre: "Rock",
    vibe: "Dark",
    energy: "Low",
    energyPeak: "Wave",
    crowdFunction: "Dance",
    vocalDemand: "Hard",
    setPosition: "Mid Set",
    reliabilityScore: "Risky",
    venueFit: "Pub",
    setFrequency: "overused",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "La Bamba",
    artist: "Ritchie Valens",
    url: "lyrics/song.html?id=labamba",
    year: 1958,
    bpm: 156,
    gender: "Male",
    genre: "Rock",
    vibe: "Romantic",
    energy: "Medium Low",
    energyPeak: "Steady",
    crowdFunction: "Emotional",
    vocalDemand: "Medium",
    setPosition: "Mid Set",
    reliabilityScore: "Risky",
    venueFit: "Flexible",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "La Grange",
    artist: "ZZ Top",
    url: "lyrics/song.html?id=lagrange",
    year: 1973,
    bpm: 162,
    gender: "Male",
    genre: "Blues",
    vibe: "Drama",
    energy: "Very High",
    energyPeak: "Steady",
    crowdFunction: "Listening",
    vocalDemand: "Hard",
    setPosition: "Build",
    reliabilityScore: "Risky",
    venueFit: "Arena style",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: false
  },
  {
    title: "Lady in Red",
    artist: "Chris de Burgh",
    url: "lyrics/song.html?id=ladyinred",
    year: 1986,
    bpm: 76,
    gender: "Male",
    genre: "Blues",
    vibe: "Drama",
    energy: "Very High",
    energyPeak: "Steady",
    crowdFunction: "Listening",
    vocalDemand: "Hard",
    setPosition: "Build",
    reliabilityScore: "Risky",
    venueFit: "Arena style",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Learn to fly",
    artist: "Foo Fighters",
    url: "lyrics/song.html?id=learntofly",
    year: 1999,
    bpm: 136,
    gender: "Male",
    genre: "Rock",
    vibe: "Drama",
    energy: "Medium Low",
    energyPeak: "Wave",
    crowdFunction: "Dance",
    vocalDemand: "Easy",
    setPosition: "Opening",
    reliabilityScore: "Moderate",
    venueFit: "Outdoor",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Legs",
    artist: "ZZ Top",
    url: "lyrics/song.html?id=legs",
    year: 1983,
    bpm: 126,
    gender: "Male",
    genre: "Blues",
    vibe: "Anthem",
    energy: "Medium High",
    energyPeak: "Wave",
    crowdFunction: "Emotional",
    vocalDemand: "Hard",
    setPosition: "Cooldown",
    reliabilityScore: "Risky",
    venueFit: "Small Acoustic",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: false
  },
  {
    title: "Let it be",
    artist: "Beatles, The",
    url: "lyrics/song.html?id=letitbe",
    year: 1970,
    bpm: 75,
    gender: "Male",
    genre: "Pop",
    vibe: "Rock",
    energy: "High",
    energyPeak: "Steady",
    crowdFunction: "Background",
    vocalDemand: "Medium",
    setPosition: "Peak",
    reliabilityScore: "Safe",
    venueFit: "Arena style",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Let me entertain you",
    artist: "Robbie Williams",
    url: "lyrics/song.html?id=letmeentertainyou",
    year: 1997,
    bpm: 125,
    gender: "Male",
    genre: "Pop",
    vibe: "Dark",
    energy: "Very Low",
    energyPeak: "Wave",
    crowdFunction: "Background",
    vocalDemand: "Medium",
    setPosition: "Build",
    reliabilityScore: "Moderate",
    venueFit: "Arena style",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Lithium",
    artist: "Nirvana",
    url: "lyrics/song.html?id=lithium",
    year: 1991,
    bpm: 123,
    gender: "Male",
    genre: "Rock",
    vibe: "Anthem",
    energy: "Very High",
    energyPeak: "Wave",
    crowdFunction: "Emotional",
    vocalDemand: "Medium",
    setPosition: "Peak",
    reliabilityScore: "Safe",
    venueFit: "Flexible",
    setFrequency: "overused",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Live Forever",
    artist: "Oasis",
    url: "lyrics/song.html?id=liveforever",
    year: 1994,
    bpm: 85,
    gender: "Male",
    genre: "Rock",
    vibe: "Chill",
    energy: "Very High",
    energyPeak: "Wave",
    crowdFunction: "Listening",
    vocalDemand: "Hard",
    setPosition: "Opening",
    reliabilityScore: "Risky",
    venueFit: "Pub",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Livin on a prayer",
    artist: "Bon Jovi",
    url: "lyrics/song.html?id=livinonaprayer",
    year: 1986,
    bpm: 121,
    gender: "Male",
    genre: "Rock",
    vibe: "Rock",
    energy: "Very High",
    energyPeak: "Drop",
    crowdFunction: "Shoutback",
    vocalDemand: "Extreme",
    setPosition: "Cooldown",
    reliabilityScore: "Safe",
    venueFit: "Outdoor",
    setFrequency: "overused",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Losing my religion",
    artist: "REM",
    url: "lyrics/song.html?id=losingmyreligion",
    year: 1991,
    bpm: 124,
    gender: "Male",
    genre: "Rock",
    vibe: "Drama",
    energy: "High",
    energyPeak: "Wave",
    crowdFunction: "Dance",
    vocalDemand: "Medium",
    setPosition: "Peak",
    reliabilityScore: "Moderate",
    venueFit: "Arena style",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Love me do",
    artist: "Beatles, The",
    url: "lyrics/song.html?id=lovemedo",
    year: 1962,
    bpm: 146,
    gender: "Male",
    genre: "Pop",
    vibe: "Chill",
    energy: "Very Low",
    energyPeak: "Wave",
    crowdFunction: "Shoutback",
    vocalDemand: "Medium",
    setPosition: "Opening",
    reliabilityScore: "Risky",
    venueFit: "Club",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Man on the moon",
    artist: "REM",
    url: "lyrics/song.html?id=manonthemoon",
    year: 1992,
    bpm: 118,
    gender: "Male",
    genre: "Rock",
    vibe: "Chill",
    energy: "Low",
    energyPeak: "Wave",
    crowdFunction: "Emotional",
    vocalDemand: "Hard",
    setPosition: "Cooldown",
    reliabilityScore: "Risky",
    venueFit: "Flexible",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Mr Brightside",
    artist: "Killers, The",
    url: "lyrics/song.html?id=mrbrightside",
    year: 2003,
    bpm: 146,
    gender: "Male",
    genre: "Indie",
    vibe: "Dark",
    energy: "Medium Low",
    energyPeak: "Building",
    crowdFunction: "Singalong",
    vocalDemand: "Hard",
    setPosition: "Cooldown",
    reliabilityScore: "Moderate",
    venueFit: "Outdoor",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Mustang Sally",
    artist: "Wilson Pickett",
    url: "lyrics/song.html?id=mustangsally",
    year: 1965,
    bpm: 110,
    gender: "Male",
    genre: "Soul",
    vibe: "Chill",
    energy: "Medium High",
    energyPeak: "Wave",
    crowdFunction: "Dance",
    vocalDemand: "Extreme",
    setPosition: "Build",
    reliabilityScore: "Safe",
    venueFit: "Arena style",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "My girl",
    artist: "Temptations, The",
    url: "lyrics/song.html?id=mygirl",
    year: 1964,
    bpm: 104,
    gender: "Male",
    genre: "Soul",
    vibe: "Romantic",
    energy: "Low",
    energyPeak: "Steady",
    crowdFunction: "Singalong",
    vocalDemand: "Easy",
    setPosition: "Opening",
    reliabilityScore: "Safe",
    venueFit: "Pub",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Nobody's wife",
    artist: "Anouk",
    url: "lyrics/song.html?id=nobodyswife",
    year: 1997,
    bpm: 98,
    gender: "Female",
    genre: "Rock",
    vibe: "Rock",
    energy: "Very High",
    energyPeak: "Drop",
    crowdFunction: "Shoutback",
    vocalDemand: "Hard",
    setPosition: "Peak",
    reliabilityScore: "Moderate",
    venueFit: "Club",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Old town road",
    artist: "Lil Nas X / Billy R Cyrus",
    url: "lyrics/song.html?id=oldtownroad",
    year: 2019,
    bpm: 68,
    gender: "Male",
    genre: "Country",
    vibe: "Drama",
    energy: "Very Low",
    energyPeak: "Wave",
    crowdFunction: "Listening",
    vocalDemand: "Easy",
    setPosition: "Peak",
    reliabilityScore: "Safe",
    venueFit: "Outdoor",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: false
  },
  {
    title: "One",
    artist: "U2",
    url: "lyrics/song.html?id=one",
    year: 1991,
    bpm: 89,
    gender: "Male",
    genre: "Rock",
    vibe: "Drama",
    energy: "Medium Low",
    energyPeak: "Building",
    crowdFunction: "Emotional",
    vocalDemand: "Hard",
    setPosition: "Mid Set",
    reliabilityScore: "Moderate",
    venueFit: "Arena style",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Otherside",
    artist: "Red Hot Chili Peppers",
    url: "lyrics/song.html?id=otherside",
    year: 1999,
    bpm: 123,
    gender: "Male",
    genre: "Rock",
    vibe: "Rock",
    energy: "Very Low",
    energyPeak: "Steady",
    crowdFunction: "Background",
    vocalDemand: "Hard",
    setPosition: "Cooldown",
    reliabilityScore: "Moderate",
    venueFit: "Flexible",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Paint it black",
    artist: "Rolling Stones",
    url: "lyrics/song.html?id=paintitblack",
    year: 1966,
    bpm: 155,
    gender: "Male",
    genre: "Rock",
    vibe: "Rock",
    energy: "High",
    energyPeak: "Building",
    crowdFunction: "Dance",
    vocalDemand: "Medium",
    setPosition: "Mid Set",
    reliabilityScore: "Moderate",
    venueFit: "Outdoor",
    setFrequency: "overused",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Paranoid",
    artist: "Black Sabbath",
    url: "lyrics/song.html?id=paranoid",
    year: 1970,
    bpm: 163,
    gender: "Male",
    genre: "Metal",
    vibe: "Drama",
    energy: "High",
    energyPeak: "Building",
    crowdFunction: "Background",
    vocalDemand: "Extreme",
    setPosition: "Mid Set",
    reliabilityScore: "Risky",
    venueFit: "Outdoor",
    setFrequency: "overused",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Penny Arcade",
    artist: "Roy Orbison",
    url: "lyrics/song.html?id=pennyarcade",
    year: 1969,
    bpm: 117,
    gender: "Male",
    genre: "Rock",
    vibe: "Chill",
    energy: "High",
    energyPeak: "Wave",
    crowdFunction: "Shoutback",
    vocalDemand: "Medium",
    setPosition: "Opening",
    reliabilityScore: "Moderate",
    venueFit: "Pub",
    setFrequency: "overused",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "People are strange",
    artist: "Doors, The",
    url: "lyrics/song.html?id=peoplearestrange",
    year: 1967,
    bpm: 117,
    gender: "Male",
    genre: "Rock",
    vibe: "Rock",
    energy: "Medium Low",
    energyPeak: "Wave",
    crowdFunction: "Shoutback",
    vocalDemand: "Medium",
    setPosition: "Cooldown",
    reliabilityScore: "Moderate",
    venueFit: "Outdoor",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Personal Jesus",
    artist: "Depeche Mode",
    url: "lyrics/song.html?id=personaljesus",
    year: 1989,
    bpm: 130,
    gender: "Male",
    genre: "Rock",
    vibe: "Anthem",
    energy: "Low",
    energyPeak: "Building",
    crowdFunction: "Emotional",
    vocalDemand: "Extreme",
    setPosition: "Mid Set",
    reliabilityScore: "Moderate",
    venueFit: "Arena style",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: false
  },
  {
    title: "Pretty Woman",
    artist: "Roy Orbison",
    url: "lyrics/song.html?id=prettywoman",
    year: 1964,
    bpm: 127,
    gender: "Male",
    genre: "Rock",
    vibe: "Dark",
    energy: "Medium",
    energyPeak: "Building",
    crowdFunction: "Shoutback",
    vocalDemand: "Extreme",
    setPosition: "Mid Set",
    reliabilityScore: "Risky",
    venueFit: "Club",
    setFrequency: "overused",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Proud Mary",
    artist: "CCR",
    url: "lyrics/song.html?id=proudmary",
    year: 1969,
    bpm: 120,
    gender: "Male",
    genre: "Rock",
    vibe: "Classic",
    energy: "Medium",
    energyPeak: "Drop",
    crowdFunction: "Background",
    vocalDemand: "Medium",
    setPosition: "Build",
    reliabilityScore: "Safe",
    venueFit: "Small Acoustic",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Psycho Killer",
    artist: "Talking Heads",
    url: "lyrics/song.html?id=psychokiller",
    year: 1977,
    bpm: 123,
    gender: "Male",
    genre: "Rock",
    vibe: "Rock",
    energy: "Medium Low",
    energyPeak: "Wave",
    crowdFunction: "Dance",
    vocalDemand: "Hard",
    setPosition: "Peak",
    reliabilityScore: "Moderate",
    venueFit: "Outdoor",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: false
  },
  {
    title: "Purple Rain",
    artist: "Prince",
    url: "lyrics/song.html?id=purplerain",
    year: 1984,
    bpm: 113,
    gender: "Male",
    genre: "Rock",
    vibe: "Drama",
    energy: "Medium Low",
    energyPeak: "Drop",
    crowdFunction: "Background",
    vocalDemand: "Medium",
    setPosition: "Mid Set",
    reliabilityScore: "Moderate",
    venueFit: "Small Acoustic",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Rebel rebel",
    artist: "David Bowie",
    url: "lyrics/song.html?id=rebelrebel",
    year: 1974,
    bpm: 126,
    gender: "Male",
    genre: "Rock",
    vibe: "Anthem",
    energy: "Very High",
    energyPeak: "Building",
    crowdFunction: "Dance",
    vocalDemand: "Medium",
    setPosition: "Opening",
    reliabilityScore: "Risky",
    venueFit: "Club",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Rebel Yell",
    artist: "Billy Idol",
    url: "lyrics/song.html?id=rebelyell",
    year: 1983,
    bpm: 166,
    gender: "Male",
    genre: "Rock",
    vibe: "Drama",
    energy: "Very High",
    energyPeak: "Wave",
    crowdFunction: "Shoutback",
    vocalDemand: "Medium",
    setPosition: "Opening",
    reliabilityScore: "Moderate",
    venueFit: "Outdoor",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: false
  },
  {
    title: "Red red wine",
    artist: "UB40",
    url: "lyrics/song.html?id=redredwine",
    year: 1983,
    bpm: 89,
    gender: "Male",
    genre: "Rock",
    vibe: "Anthem",
    energy: "Medium Low",
    energyPeak: "Steady",
    crowdFunction: "Shoutback",
    vocalDemand: "Extreme",
    setPosition: "Cooldown",
    reliabilityScore: "Moderate",
    venueFit: "Outdoor",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: false
  },
  {
    title: "Ring of fire",
    artist: "Johnny Cash",
    url: "lyrics/song.html?id=ringoffire",
    year: 1963,
    bpm: 104,
    gender: "Male",
    genre: "Country",
    vibe: "Rock",
    energy: "Medium",
    energyPeak: "Drop",
    crowdFunction: "Shoutback",
    vocalDemand: "Hard",
    setPosition: "Cooldown",
    reliabilityScore: "Risky",
    venueFit: "Small Acoustic",
    setFrequency: "overused",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Roadhouse Blues",
    artist: "Doors, The",
    url: "lyrics/song.html?id=roadhouseblues",
    year: 1970,
    bpm: 121,
    gender: "Male",
    genre: "Rock",
    vibe: "Chill",
    energy: "Medium",
    energyPeak: "Drop",
    crowdFunction: "Listening",
    vocalDemand: "Extreme",
    setPosition: "Closer",
    reliabilityScore: "Moderate",
    venueFit: "Club",
    setFrequency: "overused",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Rockin’ in the free world",
    artist: "Neil Young",
    url: "lyrics/song.html?id=rockininthefreeworld",
    year: 1989,
    bpm: 131,
    gender: "Male",
    genre: "Rock",
    vibe: "Anthem",
    energy: "Medium Low",
    energyPeak: "Steady",
    crowdFunction: "Emotional",
    vocalDemand: "Easy",
    setPosition: "Build",
    reliabilityScore: "Moderate",
    venueFit: "Outdoor",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: false
  },
  {
    title: "Ruby",
    artist: "Kaiser Chiefs",
    url: "lyrics/song.html?id=ruby",
    year: 2007,
    bpm: 93,
    gender: "Male",
    genre: "Rock",
    vibe: "Rock",
    energy: "High",
    energyPeak: "Drop",
    crowdFunction: "Emotional",
    vocalDemand: "Extreme",
    setPosition: "Build",
    reliabilityScore: "Moderate",
    venueFit: "Small Acoustic",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Runaway train",
    artist: "Soul Asylum",
    url: "lyrics/song.html?id=runawaytrain",
    year: 1992,
    bpm: 117,
    gender: "Male",
    genre: "Rock",
    vibe: "Rock",
    energy: "Medium High",
    energyPeak: "Drop",
    crowdFunction: "Background",
    vocalDemand: "Medium",
    setPosition: "Build",
    reliabilityScore: "Safe",
    venueFit: "Outdoor",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Satisfaction (I can't get no)",
    artist: "Rolling Stones",
    url: "lyrics/song.html?id=satisfactionicantgetno",
    year: 1965,
    bpm: 136,
    gender: "Male",
    genre: "Rock",
    vibe: "Dark",
    energy: "High",
    energyPeak: "Steady",
    crowdFunction: "Singalong",
    vocalDemand: "Easy",
    setPosition: "Build",
    reliabilityScore: "Safe",
    venueFit: "Arena style",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Save tonight",
    artist: "Eagle-eye Cherry",
    url: "lyrics/song.html?id=savetonight",
    year: 1997,
    bpm: 114,
    gender: "Male",
    genre: "Rock",
    vibe: "Chill",
    energy: "Very Low",
    energyPeak: "Drop",
    crowdFunction: "Emotional",
    vocalDemand: "Easy",
    setPosition: "Closer",
    reliabilityScore: "Risky",
    venueFit: "Flexible",
    setFrequency: "overused",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Scientist, The",
    artist: "Coldplay",
    url: "lyrics/song.html?id=thescientist",
    year: 2002,
    bpm: 72,
    gender: "Male",
    genre: "Pop",
    vibe: "Chill",
    energy: "High",
    energyPeak: "Drop",
    crowdFunction: "Emotional",
    vocalDemand: "Hard",
    setPosition: "Closer",
    reliabilityScore: "Risky",
    venueFit: "Arena style",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Self Esteem",
    artist: "Offspring",
    url: "lyrics/song.html?id=selfesteem",
    year: 1994,
    bpm: 105,
    gender: "Male",
    genre: "Rock",
    vibe: "Party",
    energy: "Low",
    energyPeak: "Building",
    crowdFunction: "Emotional",
    vocalDemand: "Extreme",
    setPosition: "Peak",
    reliabilityScore: "Safe",
    venueFit: "Small Acoustic",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Seven Nation Army",
    artist: "White Stripes",
    url: "lyrics/song.html?id=sevennationarmy",
    year: 2003,
    bpm: 124,
    gender: "Male",
    genre: "Rock",
    vibe: "Chill",
    energy: "High",
    energyPeak: "Drop",
    crowdFunction: "Shoutback",
    vocalDemand: "Easy",
    setPosition: "Peak",
    reliabilityScore: "Moderate",
    venueFit: "Flexible",
    setFrequency: "overused",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Sex on fire",
    artist: "Kings of Leon",
    url: "lyrics/song.html?id=sexonfire",
    year: 2008,
    bpm: 152,
    gender: "Male",
    genre: "Rock",
    vibe: "Party",
    energy: "Low",
    energyPeak: "Steady",
    crowdFunction: "Background",
    vocalDemand: "Easy",
    setPosition: "Peak",
    reliabilityScore: "Safe",
    venueFit: "Flexible",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Sharp Dressed Man",
    artist: "ZZ Top",
    url: "lyrics/song.html?id=sharpdressedman",
    year: 1983,
    bpm: 125,
    gender: "Male",
    genre: "Rock",
    vibe: "Rock",
    energy: "Medium",
    energyPeak: "Wave",
    crowdFunction: "Emotional",
    vocalDemand: "Easy",
    setPosition: "Cooldown",
    reliabilityScore: "Moderate",
    venueFit: "Arena style",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Should I stay or should I go",
    artist: "Clash, The",
    url: "lyrics/song.html?id=shouldistayorshouldigo",
    year: 1982,
    bpm: "",
    gender: "Male",
    genre: "Rock",
    vibe: "Rock",
    energy: "High",
    energyPeak: "Drop",
    crowdFunction: "Shoutback",
    vocalDemand: "Medium",
    setPosition: "Peak",
    reliabilityScore: "Safe",
    venueFit: "Club",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Simple man",
    artist: "Lynyrd Skynyrd",
    url: "lyrics/song.html?id=simpleman",
    year: 1973,
    bpm: 60,
    gender: "Male",
    genre: "Rock",
    vibe: "Party",
    energy: "Very Low",
    energyPeak: "Steady",
    crowdFunction: "Listening",
    vocalDemand: "Easy",
    setPosition: "Build",
    reliabilityScore: "Moderate",
    venueFit: "Outdoor",
    setFrequency: "overused",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Sing",
    artist: "Travis",
    url: "lyrics/song.html?id=sing",
    year: 2001,
    bpm: 80,
    gender: "Male",
    genre: "Rock",
    vibe: "Chill",
    energy: "Very High",
    energyPeak: "Wave",
    crowdFunction: "Emotional",
    vocalDemand: "Medium",
    setPosition: "Mid Set",
    reliabilityScore: "Moderate",
    venueFit: "Club",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: false
  },
  {
    title: "Smells like teen spirit",
    artist: "Nirvana",
    url: "lyrics/song.html?id=smellsliketeenspirit",
    year: 1991,
    bpm: 116,
    gender: "Male",
    genre: "Rock",
    vibe: "Chill",
    energy: "Medium Low",
    energyPeak: "Building",
    crowdFunction: "Shoutback",
    vocalDemand: "Easy",
    setPosition: "Cooldown",
    reliabilityScore: "Safe",
    venueFit: "Pub",
    setFrequency: "overused",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Smoke on the water",
    artist: "Deep Purple",
    url: "lyrics/song.html?id=smokeonthewater",
    year: 1972,
    bpm: 114,
    gender: "Male",
    genre: "Rock",
    vibe: "Drama",
    energy: "Medium Low",
    energyPeak: "Wave",
    crowdFunction: "Background",
    vocalDemand: "Extreme",
    setPosition: "Peak",
    reliabilityScore: "Moderate",
    venueFit: "Club",
    setFrequency: "overused",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "So far away",
    artist: "Dire Straits",
    url: "lyrics/song.html?id=sofaraway",
    year: 1985,
    bpm: 114,
    gender: "Male",
    genre: "Rock",
    vibe: "Drama",
    energy: "High",
    energyPeak: "Building",
    crowdFunction: "Singalong",
    vocalDemand: "Easy",
    setPosition: "Closer",
    reliabilityScore: "Risky",
    venueFit: "Flexible",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Somebody Told Me",
    artist: "Killers, The",
    url: "lyrics/song.html?id=somebodytoldme",
    year: 2004,
    bpm: 138,
    gender: "Male",
    genre: "Indie",
    vibe: "Chill",
    energy: "Very High",
    energyPeak: "Steady",
    crowdFunction: "Shoutback",
    vocalDemand: "Easy",
    setPosition: "Mid Set",
    reliabilityScore: "Safe",
    venueFit: "Outdoor",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: false
  },
  {
    title: "Stand by me - BEK",
    artist: "Ben E King",
    url: "lyrics/song.html?id=standbymebek",
    year: 1961,
    bpm: 59,
    gender: "Male",
    genre: "Rock",
    vibe: "Classic",
    energy: "High",
    energyPeak: "Building",
    crowdFunction: "Dance",
    vocalDemand: "Medium",
    setPosition: "Closer",
    reliabilityScore: "Moderate",
    venueFit: "Flexible",
    setFrequency: "overused",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Stand by Me - Oasis",
    artist: "Oasis",
    url: "lyrics/song.html?id=standbymeoasis",
    year: 1997,
    bpm: 88,
    gender: "Male",
    genre: "Rock",
    vibe: "Classic",
    energy: "High",
    energyPeak: "Building",
    crowdFunction: "Dance",
    vocalDemand: "Medium",
    setPosition: "Closer",
    reliabilityScore: "Moderate",
    venueFit: "Flexible",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Summer of ‘69",
    artist: "Bryan Adams",
    url: "lyrics/song.html?id=summerof69",
    year: 1984,
    bpm: 136,
    gender: "Male",
    genre: "Rock",
    vibe: "Romantic",
    energy: "Very Low",
    energyPeak: "Wave",
    crowdFunction: "Emotional",
    vocalDemand: "Medium",
    setPosition: "Opening",
    reliabilityScore: "Moderate",
    venueFit: "Small Acoustic",
    setFrequency: "overused",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Sunshine of your love",
    artist: "Cream",
    url: "lyrics/song.html?id=sunshineofyourlove",
    year: 1967,
    bpm: 115,
    gender: "Male",
    genre: "Rock",
    vibe: "Party",
    energy: "Medium",
    energyPeak: "Building",
    crowdFunction: "Singalong",
    vocalDemand: "Easy",
    setPosition: "Mid Set",
    reliabilityScore: "Safe",
    venueFit: "Small Acoustic",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: false
  },
  {
    title: "Sweet caroline",
    artist: "Neil Diamond",
    url: "lyrics/song.html?id=sweetcaroline",
    year: 1969,
    bpm: 128,
    gender: "Male",
    genre: "Pop",
    vibe: "Anthem",
    energy: "High",
    energyPeak: "Building",
    crowdFunction: "Singalong",
    vocalDemand: "Easy",
    setPosition: "Closer",
    reliabilityScore: "Safe",
    venueFit: "Pub",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: false
  },
  {
    title: "Sweet child o mine",
    artist: "Guns N' Roses",
    url: "lyrics/song.html?id=sweetchildomine",
    year: 1987,
    bpm: 124,
    gender: "Male",
    genre: "Rock",
    vibe: "Anthem",
    energy: "Very High",
    energyPeak: "Building",
    crowdFunction: "Singalong",
    vocalDemand: "Hard",
    setPosition: "Peak",
    reliabilityScore: "Safe",
    venueFit: "Arena style",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Sweet home Alabama",
    artist: "Lynyrd Skynyrd",
    url: "lyrics/song.html?id=sweethomealabama",
    year: 1974,
    bpm: 98,
    gender: "Male",
    genre: "Rock",
    vibe: "Dark",
    energy: "Medium High",
    energyPeak: "Drop",
    crowdFunction: "Shoutback",
    vocalDemand: "Easy",
    setPosition: "Opening",
    reliabilityScore: "Risky",
    venueFit: "Club",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Tainted Love",
    artist: "Gloria Jones",
    url: "lyrics/song.html?id=taintedlove",
    year: 1964,
    bpm: 145,
    gender: "Male",
    genre: "Rock",
    vibe: "Drama",
    energy: "Very High",
    energyPeak: "Steady",
    crowdFunction: "Dance",
    vocalDemand: "Medium",
    setPosition: "Build",
    reliabilityScore: "Moderate",
    venueFit: "Arena style",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Take me home, Country Roads",
    artist: "John Denver",
    url: "lyrics/song.html?id=takemehomecountryroads",
    year: 1971,
    bpm: 83,
    gender: "Male",
    genre: "Country",
    vibe: "Classic",
    energy: "Very Low",
    energyPeak: "Building",
    crowdFunction: "Emotional",
    vocalDemand: "Hard",
    setPosition: "Build",
    reliabilityScore: "Safe",
    venueFit: "Flexible",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: false
  },
  {
    title: "Teenage Dirtbag",
    artist: "Wheatus",
    url: "lyrics/song.html?id=teenagedirtbag",
    year: 2000,
    bpm: 95,
    gender: "Male",
    genre: "Rock",
    vibe: "Party",
    energy: "Medium Low",
    energyPeak: "Steady",
    crowdFunction: "Emotional",
    vocalDemand: "Extreme",
    setPosition: "Build",
    reliabilityScore: "Safe",
    venueFit: "Pub",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Tequila Sunrise",
    artist: "Eagles",
    url: "lyrics/song.html?id=tequilasunrise",
    year: 1973,
    bpm: 111,
    gender: "Male",
    genre: "Rock",
    vibe: "Party",
    energy: "Medium Low",
    energyPeak: "Steady",
    crowdFunction: "Emotional",
    vocalDemand: "Extreme",
    setPosition: "Build",
    reliabilityScore: "Safe",
    venueFit: "Pub",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "The Chain",
    artist: "Fleetwood Mac",
    url: "lyrics/song.html?id=thechain",
    year: 1977,
    bpm: 76,
    gender: "Female",
    genre: "Rock",
    vibe: "Drama",
    energy: "Medium High",
    energyPeak: "Building",
    crowdFunction: "Listening",
    vocalDemand: "Medium",
    setPosition: "Peak",
    reliabilityScore: "Safe",
    venueFit: "Outdoor",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "The man who sold the world",
    artist: "David Bowie",
    url: "lyrics/song.html?id=themanwhosoldtheworld",
    year: 1970,
    bpm: 115,
    gender: "Male",
    genre: "Rock",
    vibe: "Romantic",
    energy: "High",
    energyPeak: "Wave",
    crowdFunction: "Dance",
    vocalDemand: "Easy",
    setPosition: "Mid Set",
    reliabilityScore: "Safe",
    venueFit: "Pub",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: false
  },
  {
    title: "These boots are made for walking",
    artist: "Nancy Sinatra",
    url: "lyrics/song.html?id=thesebootsaremadeforwalking",
    year: 1966,
    bpm: 164,
    gender: "Female",
    genre: "Rock",
    vibe: "Drama",
    energy: "High",
    energyPeak: "Building",
    crowdFunction: "Emotional",
    vocalDemand: "Hard",
    setPosition: "Opening",
    reliabilityScore: "Safe",
    venueFit: "Club",
    setFrequency: "overused",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Three little birds",
    artist: "Bob Marley",
    url: "lyrics/song.html?id=threelittlebirds",
    year: 1977,
    bpm: 74,
    gender: "Male",
    genre: "Rock",
    vibe: "Drama",
    energy: "Medium",
    energyPeak: "Drop",
    crowdFunction: "Dance",
    vocalDemand: "Extreme",
    setPosition: "Opening",
    reliabilityScore: "Risky",
    venueFit: "Pub",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Twist and shout",
    artist: "Beatles, The",
    url: "lyrics/song.html?id=twistandshout",
    year: 1963,
    bpm: "",
    gender: "Male",
    genre: "Oldies",
    vibe: "Party",
    energy: "High",
    energyPeak: "Drop",
    crowdFunction: "Singalong",
    vocalDemand: "Medium",
    setPosition: "Peak",
    reliabilityScore: "Safe",
    venueFit: "Pub",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Two Out of Three Ain’t Bad",
    artist: "Meatloaf",
    url: "lyrics/song.html?id=twooutofthreeaintbad",
    year: 1977,
    bpm: 80,
    gender: "Male",
    genre: "Rock",
    vibe: "Anthem",
    energy: "Medium Low",
    energyPeak: "Steady",
    crowdFunction: "Background",
    vocalDemand: "Extreme",
    setPosition: "Peak",
    reliabilityScore: "Risky",
    venueFit: "Pub",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Under pressure",
    artist: "Queen",
    url: "lyrics/song.html?id=underpressure",
    year: 1981,
    bpm: 114,
    gender: "Male",
    genre: "Rock",
    vibe: "Anthem",
    energy: "High",
    energyPeak: "Building",
    crowdFunction: "Singalong",
    vocalDemand: "Hard",
    setPosition: "Peak",
    reliabilityScore: "Safe",
    venueFit: "Arena style",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Under the bridge",
    artist: "Red Hot Chili Peppers",
    url: "lyrics/song.html?id=underthebridge",
    year: 1991,
    bpm: 84,
    gender: "Male",
    genre: "Rock",
    vibe: "Drama",
    energy: "Medium Low",
    energyPeak: "Building",
    crowdFunction: "Emotional",
    vocalDemand: "Hard",
    setPosition: "Cooldown",
    reliabilityScore: "Safe",
    venueFit: "Flexible",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Valerie",
    artist: "Zutons, The",
    url: "lyrics/song.html?id=valerie",
    year: 2006,
    bpm: 94,
    gender: "Male",
    genre: "Rock",
    vibe: "Chill",
    energy: "High",
    energyPeak: "Steady",
    crowdFunction: "Shoutback",
    vocalDemand: "Hard",
    setPosition: "Build",
    reliabilityScore: "Moderate",
    venueFit: "Pub",
    setFrequency: "overused",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "What a wonderful world",
    artist: "Louis Armstrong",
    url: "lyrics/song.html?id=whatawonderfulworld",
    year: 1967,
    bpm: 70,
    gender: "Male",
    genre: "Soul",
    vibe: "Chill",
    energy: "Medium High",
    energyPeak: "Drop",
    crowdFunction: "Singalong",
    vocalDemand: "Medium",
    setPosition: "Cooldown",
    reliabilityScore: "Safe",
    venueFit: "Pub",
    setFrequency: "overused",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "What’s up",
    artist: "4 Non Blondes",
    url: "lyrics/song.html?id=whatsup",
    year: 1992,
    bpm: 67,
    gender: "Female",
    genre: "Rock",
    vibe: "Dark",
    energy: "Low",
    energyPeak: "Steady",
    crowdFunction: "Singalong",
    vocalDemand: "Extreme",
    setPosition: "Cooldown",
    reliabilityScore: "Safe",
    venueFit: "Small Acoustic",
    setFrequency: "overused",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Where is my mind",
    artist: "Pixies",
    url: "lyrics/song.html?id=whereismymind",
    year: 1988,
    bpm: 80,
    gender: "Male",
    genre: "Indie",
    vibe: "Drama",
    energy: "Medium High",
    energyPeak: "Steady",
    crowdFunction: "Emotional",
    vocalDemand: "Extreme",
    setPosition: "Opening",
    reliabilityScore: "Risky",
    venueFit: "Club",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: false
  },
  {
    title: "Wherever you will go",
    artist: "Calling, The",
    url: "lyrics/song.html?id=whereveryouwillgo",
    year: 2001,
    bpm: 110,
    gender: "Male",
    genre: "Rock",
    vibe: "Romantic",
    energy: "Low",
    energyPeak: "Drop",
    crowdFunction: "Background",
    vocalDemand: "Hard",
    setPosition: "Cooldown",
    reliabilityScore: "Risky",
    venueFit: "Outdoor",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Whiskey in the jar",
    artist: "Thin Lizzy",
    url: "lyrics/song.html?id=whiskeyinthejar",
    year: 1972,
    bpm: 128,
    gender: "Male",
    genre: "Rock",
    vibe: "Party",
    energy: "Very Low",
    energyPeak: "Building",
    crowdFunction: "Shoutback",
    vocalDemand: "Hard",
    setPosition: "Mid Set",
    reliabilityScore: "Safe",
    venueFit: "Small Acoustic",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "White Wedding",
    artist: "Billy Idol",
    url: "lyrics/song.html?id=whitewedding",
    year: 1982,
    bpm: 147,
    gender: "Male",
    genre: "Rock",
    vibe: "Party",
    energy: "Medium Low",
    energyPeak: "Wave",
    crowdFunction: "Background",
    vocalDemand: "Extreme",
    setPosition: "Mid Set",
    reliabilityScore: "Moderate",
    venueFit: "Small Acoustic",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Whole lotta rosie",
    artist: "ACDC",
    url: "lyrics/song.html?id=wholelottarosie",
    year: 1977,
    bpm: 159,
    gender: "Male",
    genre: "Metal",
    vibe: "Party",
    energy: "Very High",
    energyPeak: "Building",
    crowdFunction: "Shoutback",
    vocalDemand: "Extreme",
    setPosition: "Peak",
    reliabilityScore: "Risky",
    venueFit: "Outdoor",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: false
  },
  {
    title: "Wicked Game",
    artist: "HIM / Chris Isaak",
    url: "lyrics/song.html?id=wickedgame",
    year: 1989,
    bpm: 120,
    gender: "Male",
    genre: "Rock",
    vibe: "Dark",
    energy: "Medium High",
    energyPeak: "Building",
    crowdFunction: "Dance",
    vocalDemand: "Hard",
    setPosition: "Closer",
    reliabilityScore: "Risky",
    venueFit: "Arena style",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Wild thing",
    artist: "Troggs, The",
    url: "lyrics/song.html?id=wildthing",
    year: 1966,
    bpm: 102,
    gender: "Male",
    genre: "Rock",
    vibe: "Romantic",
    energy: "Medium Low",
    energyPeak: "Building",
    crowdFunction: "Dance",
    vocalDemand: "Medium",
    setPosition: "Closer",
    reliabilityScore: "Risky",
    venueFit: "Outdoor",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Wind of Change",
    artist: "Scorpions",
    url: "lyrics/song.html?id=windofchange",
    year: 1990,
    bpm: 76,
    gender: "Male",
    genre: "Rock",
    vibe: "Anthem",
    energy: "Medium High",
    energyPeak: "Wave",
    crowdFunction: "Shoutback",
    vocalDemand: "Extreme",
    setPosition: "Peak",
    reliabilityScore: "Safe",
    venueFit: "Outdoor",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Wish you were here",
    artist: "Pink Floyd",
    url: "lyrics/song.html?id=wishyouwerehere",
    year: 1975,
    bpm: 63,
    gender: "Male",
    genre: "Rock",
    vibe: "Dark",
    energy: "Low",
    energyPeak: "Wave",
    crowdFunction: "Singalong",
    vocalDemand: "Extreme",
    setPosition: "Closer",
    reliabilityScore: "Risky",
    venueFit: "Club",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "With or without you",
    artist: "U2",
    url: "lyrics/song.html?id=withorwithoutyou",
    year: 1987,
    bpm: 110,
    gender: "Male",
    genre: "Rock",
    vibe: "Classic",
    energy: "Medium",
    energyPeak: "Building",
    crowdFunction: "Listening",
    vocalDemand: "Extreme",
    setPosition: "Cooldown",
    reliabilityScore: "Risky",
    venueFit: "Arena style",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: false
  },
  {
    title: "Wonderful Tonight",
    artist: "Eric Clapton",
    url: "lyrics/song.html?id=wonderfultonight",
    year: 1977,
    bpm: 47/94,
    gender: "Male",
    genre: "Blues",
    vibe: "Classic",
    energy: "Very Low",
    energyPeak: "Drop",
    crowdFunction: "Dance",
    vocalDemand: "Easy",
    setPosition: "Mid Set",
    reliabilityScore: "Risky",
    venueFit: "Arena style",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Wonderwall",
    artist: "Oasis",
    url: "lyrics/song.html?id=wonderwall",
    year: 1995,
    bpm: 87,
    gender: "Male",
    genre: "Rock",
    vibe: "Drama",
    energy: "Medium Low",
    energyPeak: "Drop",
    crowdFunction: "Background",
    vocalDemand: "Medium",
    setPosition: "Peak",
    reliabilityScore: "Risky",
    venueFit: "Pub",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Word up",
    artist: "Cameo / Korn",
    url: "lyrics/song.html?id=wordup",
    year: 1986,
    bpm: 116,
    gender: "Male",
    genre: "Rock",
    vibe: "Chill",
    energy: "Medium Low",
    energyPeak: "Steady",
    crowdFunction: "Emotional",
    vocalDemand: "Easy",
    setPosition: "Cooldown",
    reliabilityScore: "Safe",
    venueFit: "Arena style",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: false
  },
  {
    title: "Xemx",
    artist: "Tramps, The",
    url: "lyrics/song.html?id=xemx",
    year: 1975,
    bpm: 56/112,
    gender: "Male",
    genre: "Rock",
    vibe: "Classic",
    energy: "Medium High",
    energyPeak: "Drop",
    crowdFunction: "Listening",
    vocalDemand: "Easy",
    setPosition: "Cooldown",
    reliabilityScore: "Risky",
    venueFit: "Arena style",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Yellow",
    artist: "Coldplay",
    url: "lyrics/song.html?id=yellow",
    year: 2000,
    bpm: 86,
    gender: "Male",
    genre: "Pop",
    vibe: "Classic",
    energy: "Medium Low",
    energyPeak: "Drop",
    crowdFunction: "Singalong",
    vocalDemand: "Extreme",
    setPosition: "Build",
    reliabilityScore: "Moderate",
    venueFit: "Arena style",
    setFrequency: "normal",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "You sexy thing",
    artist: "Hot Chocolate",
    url: "lyrics/song.html?id=yousexything",
    year: 1975,
    bpm: 105,
    gender: "Male",
    genre: "Rock",
    vibe: "Anthem",
    energy: "High",
    energyPeak: "Drop",
    crowdFunction: "Background",
    vocalDemand: "Medium",
    setPosition: "Closer",
    reliabilityScore: "Moderate",
    venueFit: "Small Acoustic",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "You spin me round",
    artist: "Dead or Alive",
    url: "lyrics/song.html?id=youspinmeround",
    year: 1984,
    bpm: 129,
    gender: "Male",
    genre: "Rock",
    vibe: "Chill",
    energy: "Very High",
    energyPeak: "Wave",
    crowdFunction: "Dance",
    vocalDemand: "Hard",
    setPosition: "Build",
    reliabilityScore: "Moderate",
    venueFit: "Flexible",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: false
  },
  {
    title: "Zombie",
    artist: "Cranberries, The",
    url: "lyrics/song.html?id=zombie",
    year: 1993,
    bpm: 81,
    gender: "Female",
    genre: "Rock",
    vibe: "Anthem",
    energy: "Medium",
    energyPeak: "Building",
    crowdFunction: "Background",
    vocalDemand: "Extreme",
    setPosition: "Mid Set",
    reliabilityScore: "Risky",
    venueFit: "Arena style",
    setFrequency: "overused",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "My Way",
    artist: "Frank Sinatra",
    url: "lyrics/song.html?id=myway",
    year: 1969,
    bpm: 75,
    gender: "Male",
    genre: "Oldies",
    vibe: "Anthem",
    energy: "Medium Low",
    energyPeak: "Building",
    crowdFunction: "Emotional",
    vocalDemand: "Hard",
    setPosition: "Closer",
    reliabilityScore: "Safe",
    venueFit: "Flexible",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "Redemption Song",
    artist: "Bob Marley",
    url: "lyrics/song.html?id=redemptionsong",
    year: 1980,
    bpm: 115,
    gender: "Male",
    genre: "Folk",
    vibe: "Drama",
    energy: "Low",
    energyPeak: "Building",
    crowdFunction: "Listening",
    vocalDemand: "Medium",
    setPosition: "Cooldown",
    reliabilityScore: "Safe",
    venueFit: "Small Acoustic",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  },
  {
    title: "My Sweet Lord",
    artist: "George Harrison",
    url: "lyrics/song.html?id=mysweetlord",
    year: 1970,
    bpm: 120,
    gender: "Male",
    genre: "Folk",
    vibe: "Drama",
    energy: "Low",
    energyPeak: "Building",
    crowdFunction: "Listening",
    vocalDemand: "Medium",
    setPosition: "Cooldown",
    reliabilityScore: "Safe",
    venueFit: "Small Acoustic",
    setFrequency: "rare",
    hostKaraokePage: "1",
    livePage: "1",
    hasLyrics: true
  }
];
