const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {parseHTML}=require(require.resolve('linkedom',{paths:[process.env.LS26_TEST_NODE_MODULES||process.cwd()]}));
const model=require('../shared/timing-model.js'),playback=require('../shared/chord-playback.js'),follow=require('../shared/lyricview-chord-follow.js'),transport=require('../shared/musical-transport.js');
async function fixture({untimed=false,partial=false,review=false,collapsed=false}={}){
 const {window,document}=parseHTML('<html><body><div id="ls26StickyHeader"></div><div id="lyricsContent"></div><div class="host-bottom-dock"><div class="host-scroll-player"></div></div></body></html>');
 const song={timeSignature:'4/4',sections:[{type:'lyrics',title:'INTRO',html:'G D G'},{type:'lyrics',title:'VERSE',html:'<strong>C/G</strong> <span>Bbmaj7/D</span>'},{type:'hostNote',title:'REFERENCE',text:'G D G C'}]};
 const bodies=new Map();song.sections.forEach((s,i)=>{const card=document.createElement('section');card.className='host-section';card.dataset.sectionIndex=i;const body=document.createElement('div');body.className='host-section-body';body.innerHTML=s.html||s.text;card.append(body);document.getElementById('lyricsContent').append(card);bodies.set(i,body);});
 let timing=await model.createDraft(await model.buildSource(song,document));for(const [i,value]of [4,2,3.5,.5,2].entries())timing=model.setDuration(timing,timing.events[i].id,value);timing.revision=1;
 if(partial)timing=model.setDuration(timing,timing.events[2].id,null);if(review)timing.reviewReasons.push('meter-changed');if(collapsed)document.querySelector('.host-section').classList.add('collapsed');
 let now=0,reads=0,finished=0;const clock=transport.create({now:()=>now,bpm:120}),sections=[],scrolls=[],frames=new Map();let frame=0;
 window.scrollY=0;window.innerHeight=800;window.innerWidth=768;window.matchMedia=()=>({matches:true});window.requestAnimationFrame=fn=>{frames.set(++frame,fn);return frame;};window.cancelAnimationFrame=id=>frames.delete(id);
 window.scrollBy=value=>{scrolls.push(value);window.scrollY+=value.top;};
 window.HTMLElement.prototype.getBoundingClientRect=function(){
  if(this.id==='ls26StickyHeader')return {top:0,bottom:100,height:100};if(this.classList.contains('host-bottom-dock'))return {top:720,bottom:800,height:80};
  const index=[...document.querySelectorAll('.ls26-timed-chord')].indexOf(this),absolute=index<3?200:900+(index-3)*80;return {top:absolute-window.scrollY,bottom:absolute-window.scrollY+25,height:25,left:10,right:100};
 };
 const api=follow.mount({document,window,songId:'fixture',getSong:()=>song,store:{async load(){reads++;return untimed?{status:'UNTIMED',timing:null}:{status:model.status(timing),timing};}},getAudio:()=>clock,onSection:i=>sections.push(i),onFinish:()=>finished++});
 return {window,document,api,clock,timing,song,bodies,sections,scrolls,frames,time:t=>now=t,get reads(){return reads;},get finished(){return finished;}};
}
test('ordered timeline has exact fractional boundaries, repeated IDs and no chord-text identity',async()=>{const e=await fixture(),t=playback.timeline(e.timing);assert.equal(t.totalBeats,12);for(const [beat,index]of [[0,0],[3.999,0],[4,1],[6,2],[9.5,3],[10,4],[11.999,4]])assert.equal(t.at(beat).index,index);assert.equal(t.at(-1),null);assert.equal(t.at(12),null);assert.notEqual(t.events[0].id,t.events[2].id);});
test('render mapping preserves exact text, whitespace, repeated symbols and slash occurrences',async()=>{const e=await fixture(),before=[...e.bodies.values()].map(b=>b.textContent),nodes=playback.bind(e.timing.events,e.bodies,e.document);assert.equal(nodes.size,5);assert.notEqual(nodes.get(e.timing.events[0].id),nodes.get(e.timing.events[2].id));assert.deepEqual([...e.bodies.values()].map(b=>b.textContent),before);assert.equal(nodes.get(e.timing.events[3].id).textContent,'C/G');assert.equal(e.document.querySelectorAll('[data-event-id]').length,0);});
test('render mismatch fails before any wrapper or highlight is applied',async()=>{const e=await fixture();e.bodies.get(0).textContent='G D C';assert.throws(()=>playback.bind(e.timing.events,e.bodies,e.document),/match/);assert.equal(e.document.querySelectorAll('.ls26-timed-chord').length,0);});
test('Viewer loads timing lazily once and progresses current chord/section using only transport position',async()=>{const e=await fixture();assert.equal(e.reads,0);assert.equal(await e.api.enable(),true);assert.equal(e.reads,1);e.clock.start();
 for(const [time,index]of [[0,0],[2,1],[3,2],[4.75,3],[5,4]]){e.time(time);e.api.update();assert.equal(e.api.snapshot().index,index);const highlighted=e.document.querySelectorAll('.ls26-active-chord');assert.equal(highlighted.length,1);assert.equal(highlighted[0].textContent,e.timing.events[index].chord);}
 assert.deepEqual(e.sections,[0,0,0,1,1]);assert.equal(e.reads,1);e.api.disable();await e.api.enable();assert.equal(e.reads,1);assert.equal(e.clock.getBeat(),0);e.api.disable();});
test('paused clock keeps chord; resume/BPM changes preserve transport correspondence',async()=>{const e=await fixture();await e.api.enable();e.clock.start();e.time(2);e.api.update();e.clock.pause();e.time(40);e.api.update();assert.equal(e.api.snapshot().index,1);e.clock.resume();e.clock.setBpm(60);e.time(42);e.api.update();assert.equal(e.api.snapshot().index,2);assert.equal(e.reads,1);e.api.disable();});
test('untimed, partial and needs-review songs leave normal fallback available without starting transport',async()=>{for(const options of [{untimed:true},{partial:true},{review:true},{collapsed:true}]){const e=await fixture(options);assert.equal(await e.api.enable(),false);assert.equal(e.api.enabled(),false);assert.equal(e.clock.snapshot().state,'stopped');assert.equal(e.document.querySelectorAll('.ls26-active-chord').length,0);assert.equal(e.reads,1);}});
test('timeline finishes at total musical beats once, retaining final highlight',async()=>{const e=await fixture();await e.api.enable();e.clock.start();e.time(5.5);e.api.update();e.time(6);e.api.update();e.api.update();assert.equal(e.finished,1);assert.equal(e.clock.snapshot().state,'paused');assert.equal(e.api.snapshot().index,4);e.api.disable();});

test('same visible line never wiggles; a departing new line moves into the focus area',async()=>{const e=await fixture();await e.api.enable();e.clock.start();e.time(2);e.api.update();e.time(3);e.api.update();assert.equal(e.scrolls.length,0);e.time(4.75);e.api.update();assert.equal(e.scrolls.length,1);assert.ok(e.scrolls[0].top>0);e.time(5);e.api.update();assert.equal(e.scrolls.length,1,'already comfortable upcoming line needs no motion');e.api.disable();});
test('anticipation happens once near the chord end, is bounded, and retains current highlight',async()=>{const e=await fixture();await e.api.enable();e.clock.start();e.time(4.55);e.api.update();assert.equal(e.api.snapshot().index,2);assert.equal(e.scrolls.length,1);assert.ok(e.scrolls[0].top<=210);e.time(4.56);e.api.update();assert.equal(e.scrolls.length,1);assert.equal(e.document.querySelector('.ls26-active-chord').textContent,'G');e.api.disable();});
test('manual override survives section transitions while highlights progress; rejoin preserves beat',async()=>{const e=await fixture();await e.api.enable();e.clock.start();e.api.suspend();e.time(4.75);e.api.update();assert.equal(e.api.snapshot().index,3);assert.equal(e.api.snapshot().manual,true);assert.equal(e.scrolls.length,0);assert.equal(e.document.getElementById('rejoinChordBtn').hidden,false);const beat=e.clock.getBeat();e.api.rejoin();assert.equal(e.clock.getBeat(),beat);assert.equal(e.api.snapshot().manual,false);assert.equal(e.scrolls.length,1);e.time(5);e.api.update();assert.equal(e.api.snapshot().index,4);assert.equal(e.reads,1);e.api.disable();});
test('wheel during own smooth positioning immediately suspends, and scrollbar scrolls also suspend',async()=>{const e=await fixture();await e.api.enable();e.clock.start();e.api.rejoin();e.window.dispatchEvent(new e.window.Event('wheel'));assert.equal(e.api.snapshot().manual,true);e.api.disable();await e.api.enable();e.window.scrollY+=30;e.window.dispatchEvent(new e.window.Event('scroll'));assert.equal(e.api.snapshot().manual,true);e.api.disable();});
test('tablet touch drag suspends positioning while chord time and highlighting continue',async()=>{const e=await fixture();await e.api.enable();e.clock.start();const chord=e.document.querySelector('.ls26-active-chord');
 const touch=(type,y)=>{const event=new e.window.Event(type,{bubbles:true});Object.defineProperty(event,'touches',{value:[{clientX:100,clientY:y}]});chord.dispatchEvent(event);};
 touch('touchstart',200);touch('touchmove',205);assert.equal(e.api.snapshot().manual,false);touch('touchmove',220);assert.equal(e.api.snapshot().manual,true);
 e.time(4.75);e.api.update();assert.equal(e.api.snapshot().index,3);assert.equal(e.document.querySelector('.ls26-active-chord').textContent,'C/G');assert.equal(e.scrolls.length,0);e.api.rejoin();assert.equal(e.api.snapshot().manual,false);assert.equal(e.clock.getBeat(),9.5);e.api.disable();});
test('keyboard text entry does not claim manual override and explicit reset restarts musical zero',async()=>{const e=await fixture();await e.api.enable();e.clock.start();e.time(3);e.api.update();const input=e.document.createElement('input');e.document.body.append(input);const event=new e.window.Event('keydown',{bubbles:true});Object.defineProperty(event,'key',{value:'ArrowDown'});input.dispatchEvent(event);assert.equal(e.api.snapshot().manual,false);e.api.reset();assert.equal(e.clock.getBeat(),0);assert.equal(e.api.snapshot().index,0);assert.equal(e.clock.snapshot().state,'stopped');e.api.disable();});

test('actual Viewer/metronome share one audio transport, preserve pause/BPM and never write timing during playback',async()=>{
 const {setup:actual,tick,song}=require('../verification/chord-foundation-pages.cjs'),e=actual('lyricview');for(let i=0;i<10;i++)await tick();
 let saved=await e.window.LS26Timing.createDraft(await e.window.LS26Timing.buildSource(song,e.document));for(const event of saved.events)saved=e.window.LS26Timing.setDuration(saved,event.id,2);saved.revision=1;e.window.__fixture.data['lyrics/song0/musicalTiming/v1']=JSON.parse(JSON.stringify(saved));
 let context;const intervals=new Map();let next=0;const param=()=>({setValueAtTime(){},exponentialRampToValueAtTime(){}});
 e.window.AudioContext=class{constructor(){context=this;this.currentTime=0;this.state='suspended';this.destination={};}async resume(){this.state='running';}createGain(){return {gain:param(),connect(){},disconnect(){}};}createOscillator(){return {frequency:param(),connect(){},disconnect(){},start(){},stop(){}};}};
 e.window.setInterval=fn=>{intervals.set(++next,fn);return next;};e.window.clearInterval=id=>intervals.delete(id);
 e.run('shared/lyricview-metronome.js');const metro=e.document.createElement('section');e.document.body.append(metro);e.window.LS26LyricMetronome.mount(metro);
 assert.equal(e.window.__fixture.calls.filter(c=>c[1].includes('/musicalTiming/')).length,0);assert.equal(await e.window.LS26TimedView.enable(),true);
 e.window.LS26Performance.setBpm(120);e.window.LS26Performance.play();for(let i=0;i<10;i++)await tick();
 assert.equal(intervals.size,1);const driver=e.window.LS26Click.driver();assert.equal(driver.context,context);assert.equal(driver.snapshot().state,'playing');
 context.currentTime=2.05;e.window.LS26TimedView.update();assert.equal(e.window.LS26TimedView.snapshot().index,2);
 const third=e.document.querySelector('.ls26-active-chord');e.window.__testTranspose(2);e.window.LS26TimedView.update();assert.equal(e.document.querySelector('.ls26-active-chord'),third);assert.equal(third.textContent.trim(),'A');assert.match(e.document.getElementById('chordFollowStatus').textContent,/A · chord 3/);
 e.document.getElementById('autoScrollBtn').onclick();assert.equal(driver.snapshot().state,'paused');const held=driver.getBeat();context.currentTime=50;assert.equal(driver.getBeat(),held);
 e.document.getElementById('autoScrollBtn').onclick();await tick();assert.equal(driver.context,context);assert.equal(driver.snapshot().state,'playing');
 e.window.LS26Performance.setBpm(60);context.currentTime=52;e.window.LS26TimedView.update();assert.equal(driver.getBeat(),held+2);assert.equal(e.window.LS26TimedView.snapshot().index,3);
 assert.equal(e.window.__fixture.calls.filter(c=>c[0]==='get'&&c[1].includes('/musicalTiming/')).length,1);assert.equal(e.window.__fixture.calls.filter(c=>c[0]==='set'&&c[1].includes('/musicalTiming/')).length,0);
 assert.equal(JSON.stringify(e.window.__fixture.data['lyrics/song0/musicalTiming/v1']),JSON.stringify(saved));e.window.LS26TimedView.disable();e.window.LS26Click.stop();assert.equal(intervals.size,0);
});

test('incomplete follow exposes exact counts in a readable full-width panel',async()=>{const e=await fixture({partial:true});await e.api.enable();const status=e.document.getElementById('chordFollowStatus');assert.equal(status.hidden,false);assert.equal(status.parentElement.className,'host-bottom-dock');assert.equal(status.closest('.host-scroll-player'),null);assert.match(status.textContent,/CHORD FOLLOW UNAVAILABLE\n4 of 5 chords are timed\.\n1 chord still needs timing\./);assert.equal(status.classList.contains('is-unavailable'),true);assert.deepEqual(e.api.snapshot().completeness,{total:5,timed:4,untimed:1,unresolved:0,unresolvedTimed:0,meterNeedsReview:false,needsReview:false,ready:false});e.api.disable();});
test('review-required follow remains blocked and names the meter review reason',async()=>{const e=await fixture({review:true});assert.equal(await e.api.enable(),false);assert.match(e.document.getElementById('chordFollowStatus').textContent,/5 of 5 chords are timed\.[\s\S]*meter needs review/);assert.equal(e.api.snapshot().completeness.needsReview,true);assert.equal(e.api.enabled(),false);});
test('untimed follow states that no saved document exists without creating one',async()=>{const e=await fixture({untimed:true});assert.equal(await e.api.enable(),false);assert.match(e.document.getElementById('chordFollowStatus').textContent,/No saved timing exists/);assert.equal(e.reads,1);});
test('dock separates player controls, timeline, follow group and persistent notification',async()=>{const e=await fixture();const dock=e.document.querySelector('.host-bottom-dock'),player=dock.querySelector('.host-scroll-player'),group=player.querySelector('.chord-follow-actions');assert.ok(group);assert.equal(group.querySelector('#chordFollowBtn').textContent,'FOLLOW: OFF');assert.equal(group.querySelector('#rejoinChordBtn').hidden,true);assert.equal(dock.querySelector('#chordFollowStatus').parentNode,dock);
 const css=fs.readFileSync(require('node:path').join(__dirname,'../host/css/lyricview-fixes.css'),'utf8');assert.match(css,/body\.host-lyric-view-page \.host-bottom-dock\{[^}]*height:auto!important/);assert.match(css,/\.host-scroll-player button\{[^}]*white-space:nowrap!important/);assert.match(css,/@media\(max-width:900px\)/);assert.match(css,/--lv-dock-height/);assert.match(css,/#chordFollowStatus\{[^}]*overflow:visible!important/);
 await e.api.enable();assert.equal(group.querySelector('#chordFollowBtn').textContent,'FOLLOW: ON');e.api.suspend();assert.equal(group.querySelector('#rejoinChordBtn').hidden,false);e.api.rejoin();assert.equal(group.querySelector('#rejoinChordBtn').hidden,true);e.api.disable();});
