const {test}=require('node:test'),assert=require('node:assert/strict');
const {setup,tick,song}=require('../verification/chord-foundation-pages.cjs');
async function creator(){const e=setup('lyricscreator');e.window.auth.currentUser.getIdTokenResult=async()=>({claims:{email:'leeborg23@gmail.com'}});for(let i=0;i<10;i++)await tick();e.api=e.window.LS26CreatorTiming;e.btn=e.document.getElementById('saveSongBtn');e.edit=()=>{const input=e.document.getElementById('songTitleInput');input.value+=' edit';input.dispatchEvent(new e.window.Event('input',{bubbles:true}));};e.unload=()=>{const event=new e.window.Event('beforeunload',{cancelable:true});e.window.dispatchEvent(event);return event.defaultPrevented;};return e;}
const saved=async e=>{let t=await e.window.LS26Timing.createDraft(await e.window.LS26Timing.buildSource(song,e.document));for(const ev of t.events)t=e.window.LS26Timing.setDuration(t,ev.id,2);t.revision=1;e.window.__fixture.data['lyrics/song0/musicalTiming/v1']=JSON.parse(JSON.stringify(t));};
test('cancel custom leave and native unload retain actual song dirty/save state',async()=>{const e=await creator();assert.equal(e.btn.disabled,true);e.edit();assert.equal(e.btn.disabled,false);assert.equal(e.unload(),true);assert.equal(e.btn.disabled,false);e.window.LS26Dialogs.confirm=async()=>false;await e.document.getElementById('cancelChangesBtn').onclick();assert.equal(e.btn.disabled,false);assert.equal(e.unload(),true);assert.equal(e.window.__fixture.calls.filter(c=>c[0]==='set').length,0);});
test('ordinary song Save finishes without a native unload warning and disables Save',async()=>{const e=await creator();e.edit();await e.btn.onclick();assert.equal(e.unload(),false);assert.equal(e.btn.disabled,true);assert.match(e.ctx.location.href,/lyricview/);});
test('source-only update keeps timing draft after Song Save without asking about manual timing',async()=>{const e=await creator();await saved(e);const editor=e.document.querySelector('[data-html="0"]');editor.innerHTML+='<br>A F';editor.dispatchEvent(new e.window.Event('input',{bubbles:true}));await e.api.enter();assert.equal(e.api.snapshot().sourceChanged,true);assert.equal(e.api.snapshot().manualDirty,false);e.window.LS26Dialogs.confirm=async()=>true;await e.api.exit();await e.btn.onclick();assert.equal(e.btn.disabled,true);assert.equal(e.unload(),false);assert.match(e.ctx.location.href,/lyricscreator/);assert.equal(e.api.snapshot().sourceChanged,true);assert.equal(e.window.__fixture.calls.filter(c=>c[0]==='set'&&c[1].includes('musicalTiming')).length,0);});
test('Save Both cancellation retains song and timing edits, button state and draft',async()=>{const e=await creator();e.edit();await e.api.enter();e.api.step(.5);let request;e.window.LS26Dialogs.choose=async(text,options)=>{request={text,options};return null;};await e.btn.onclick();assert.equal(e.btn.disabled,false);assert.equal(e.api.snapshot().manualDirty,true);assert.equal(e.unload(),true);assert.equal(e.window.__fixture.calls.filter(c=>c[0]==='set').length,0);assert.deepEqual(Array.from(request.options.choices,c=>c.label),['SAVE BOTH','SAVE SONG ONLY']);});
test('Save Song Only retains manual timing on page; successful song Save clears only song dirty',async()=>{const e=await creator();e.edit();await e.api.enter();e.api.step(.5);e.window.LS26Dialogs.choose=async()=> 'song';await e.btn.onclick();assert.equal(e.btn.disabled,true);assert.equal(e.api.snapshot().manualDirty,true);assert.match(e.ctx.location.href,/lyricscreator/);assert.equal(e.window.__fixture.calls.filter(c=>c[0]==='set'&&c[1].includes('musicalTiming')).length,0);assert.equal(e.unload(),true);});
test('Save Both uses existing compact timing transaction and clears both states',async()=>{const e=await creator();e.edit();await e.api.enter();e.api.step(1.5);const id=e.api.snapshot().selectedId;e.window.LS26Dialogs.choose=async()=> 'both';await e.btn.onclick();assert.equal(e.btn.disabled,true);assert.equal(e.api.snapshot().dirty,false);assert.equal(e.api.snapshot().manualDirty,false);assert.equal(e.api.snapshot().selectedId,id);assert.equal(e.unload(),false);assert.equal(e.window.__fixture.calls.filter(c=>c[0]==='set'&&c[1].includes('musicalTiming')).length,1);assert.equal(e.window.__fixture.data['lyrics/song0/musicalTiming/v1'].events[0].durationBeats,1.5);assert.equal(e.window.__fixture.data['lyrics/song0'].musicalTiming,undefined);});
test('failed timing save after Song Save preserves timing draft and reports partial success',async()=>{const e=await creator();e.edit();await e.api.enter();e.api.step(.5);e.window.LS26Dialogs.choose=async()=> 'both';let notice;e.window.LS26Dialogs.alert=async text=>notice=text;e.window.__fixture.data['lyrics/song0/musicalTiming/v1']={...e.api.snapshot().draft,revision:1};await e.btn.onclick();assert.equal(e.btn.disabled,true);assert.equal(e.api.snapshot().manualDirty,true);assert.match(notice,/song was saved.*draft is still here/);assert.equal(e.api.snapshot().conflict,'TIMING_CHANGED');assert.match(e.ctx.location.href,/lyricscreator/);});
test('LiveSuite multi-action dialog cancels safely and returns only an explicit Save choice',async()=>{
 const fs=require('node:fs'),vm=require('node:vm'),{parseHTML}=require(require.resolve('linkedom',{paths:[process.env.LS26_TEST_NODE_MODULES]})),{window,document}=parseHTML('<html><body></body></html>');
 const create=document.createElement.bind(document);document.createElement=tag=>{const el=create(tag);if(tag==='dialog'){el.showModal=()=>{};el.close=()=>el.dispatchEvent(new window.Event('close'));}return el;};
 vm.runInNewContext(fs.readFileSync(require('node:path').join(__dirname,'../shared/dialogs.js'),'utf8'),{window,document,MutationObserver:class{observe(){}},matchMedia:()=>({matches:true}),setTimeout:fn=>fn()});
 const options={title:'Unsaved song and timing',choices:[{value:'both',label:'SAVE BOTH'},{value:'song',label:'SAVE SONG ONLY'}]};
 const cancel=window.LS26Dialogs.choose('Keep drafts?',options);document.querySelector('.ls26-modal-x').click();assert.equal(await cancel,null);
 const songOnly=window.LS26Dialogs.choose('Keep drafts?',options);document.querySelector('[data-choice="song"]').click();assert.equal(await songOnly,'song');
 const both=window.LS26Dialogs.choose('Keep drafts?',options);document.querySelector('[data-choice="both"]').click();assert.equal(await both,'both');
 const legacy=window.LS26Dialogs.confirm('Leave?');document.querySelector('form').dispatchEvent(new window.Event('submit',{cancelable:true}));assert.equal(await legacy,true);assert.equal(document.querySelectorAll('dialog').length,0);
});
test('edits made while Song Save is pending retain dirty state and keep the editor open',async()=>{const e=await creator();e.edit();let release;const db=e.window.db,collection=db.collection.bind(db);db.collection=name=>{const ref=collection(name);if(name==='lyrics'){const doc=ref.doc.bind(ref);ref.doc=id=>{const record=doc(id),set=record.set.bind(record);record.set=async(...args)=>{await new Promise(resolve=>release=resolve);return set(...args);};return record;};}return ref;};const work=e.btn.onclick();await tick();e.edit();release();await work;assert.equal(e.btn.disabled,false);assert.equal(e.unload(),true);assert.match(e.ctx.location.href,/lyricscreator/);assert.notEqual(e.document.getElementById('songTitleInput').value,e.window.__fixture.data['lyrics/song0'].title);});
