const {test}=require('node:test'),assert=require('node:assert/strict');
const transport=require('../shared/musical-transport.js'),tap=require('../shared/tap-timing.js'),engine=require('../shared/metronome-engine.js'),audio=require('../shared/song-audio.js');
function fixture(){let now=0;const clock=transport.create({now:()=>now,bpm:120}),events=['G','D','G','C/G','Bbmaj7/D'].map((chord,i)=>({id:'event'+i,chord})),values=new Map(),selected=[];
 const session=tap.create({clock,events,getDuration:id=>values.get(id),onDuration:(id,value)=>value===null?values.delete(id):values.set(id,value),onSelect:index=>selected.push(index)});
 return {clock,session,events,values,selected,time:value=>now=value};}
test('half-beat quantization rounds nearest; positive short taps clamp to 0.5',()=>{for(const [raw,expected]of [[3.87,4],[2.28,2.5],[.01,.5],[.5,.5],[1.5,1.5],[2.5,2.5],[3.5,3.5],[1.25,1.5]])assert.equal(tap.quantize(raw),expected);assert.throws(()=>tap.quantize(0));});
test('capture distinguishes repeated/slash chords and has no storage dependencies',()=>{const e=fixture();e.session.begin();e.clock.start();for(const [i,seconds]of [2,3.25,4,4.25,6].entries()){e.time(seconds);assert.ok(e.session.capture());}assert.deepEqual([...e.values.values()],[4,2.5,1.5,.5,3.5]);assert.equal(e.session.snapshot().complete,true);assert.equal(e.session.capture(),false);assert.equal(e.events[0].chord,e.events[2].chord);assert.notEqual(e.events[0].id,e.events[2].id);});
test('BPM changes preserve elapsed musical structure and pause excludes wall time',()=>{const e=fixture();e.session.begin();e.clock.start();e.time(1);e.clock.setBpm(60);e.time(2);e.clock.pause();e.time(20);assert.equal(e.session.capture(),false);e.clock.resume();e.time(21);assert.equal(e.session.capture().duration,4);assert.equal(e.clock.getBeat(),4);});
test('count-in is excluded from first duration and tap is disabled before song zero',()=>{const e=fixture();e.session.begin();e.clock.start({countInBeats:4});e.time(1);assert.equal(e.session.capture(),false);e.time(2);assert.equal(e.session.capture(),false);e.time(4);assert.equal(e.session.capture().duration,4);});
test('mistap undo restores selection, duration and original chord start without rewinding clock',()=>{const e=fixture();e.values.set('event0',8);e.session.begin();e.clock.start();e.time(1);e.session.capture();assert.equal(e.session.snapshot().index,1);e.time(1.5);assert.equal(e.session.undo(),true);assert.equal(e.session.snapshot().index,0);assert.equal(e.session.snapshot().startBeat,0);assert.equal(e.values.get('event0'),8);assert.equal(e.clock.getBeat(),3);e.time(2);assert.equal(e.session.capture().duration,4);});
test('transport scheduler keeps absolute phase over BPM changes and stalls',()=>{let now=0;const clock=transport.create({now:()=>now,bpm:120}),settings={...engine.normalize({bpm:120,beats:3}),beatUnit:8},clicks=[];clock.start();let scheduler=new engine.TransportClock(clock,()=>settings,e=>clicks.push(e));scheduler.schedule(now);now=.25;scheduler.schedule(now);assert.equal(clicks[1].position,.5);assert.equal(clicks[1].beat,1);clock.setBpm(60);scheduler=new engine.TransportClock(clock,()=>settings,e=>clicks.push(e));now=.75;scheduler.schedule(now);assert.equal(clicks.at(-1).position,1);const before=clicks.length;now=10000;scheduler.schedule(now);assert.ok(clicks.length-before<2);assert.equal(clock.getBeat(),10000.25);});
function fakeAudio(){let ctx;const timers=new Map(),sounds=[];let next=0;const param=()=>({setValueAtTime(){},exponentialRampToValueAtTime(){}});const window={addEventListener(){},document:{addEventListener(){}},setInterval:fn=>{timers.set(++next,fn);return next;},clearInterval:id=>timers.delete(id),AudioContext:class{constructor(){ctx=this;this.currentTime=0;this.state='suspended';this.destination={};}async resume(){this.state='running';}createGain(){return {gain:param(),connect(){},disconnect(){}};}createOscillator(){const sound={frequency:param(),connect(){},disconnect(){},start(t){this.time=t;},stop(){this.stopped=true;}};sounds.push(sound);return sound;}}};return {window,timers,sounds,context:()=>ctx,tick:()=>[...timers.values()].forEach(fn=>fn())};}
test('audio driver shares one context, cancels queued clicks on pause/BPM, and keeps beat position',async()=>{const e=fakeAudio(),settings={bpm:120,beats:4,volume:65};const driver=audio.create({window:e.window,getSettings:()=>settings});assert.equal(e.context(),undefined);await driver.start({countInBeats:4});const ctx=e.context();assert.equal(e.timers.size,1);ctx.currentTime=2.05;assert.ok(Math.abs(driver.getBeat())<1e-8);e.tick();ctx.currentTime=3.05;driver.pause();assert.equal(e.timers.size,0);assert.equal(driver.getBeat(),2);ctx.currentTime=20;assert.equal(driver.getBeat(),2);await driver.resume();assert.equal(e.context(),ctx);ctx.currentTime=21;driver.setBpm(60);ctx.currentTime=22;assert.equal(driver.getBeat(),5);driver.stop();assert.equal(driver.getBeat(),0);assert.equal(e.timers.size,0);assert.ok(e.sounds.every(s=>s.stopped));});
