(() => {
  const $=id=>document.getElementById(id); const firebaseId=new URLSearchParams(location.search).get("firebaseId");
  let sections=[]; let loadedSong=null;
  function esc(v){return LyricsCommon.escapeHTML(v);}
  function makeSection(type){if(type==="separator")return{type:"separator"};if(type==="performanceNote")return{type:"performanceNote",title:"Performance Note",text:"Short instrumental (wait for signal)"};if(type==="tab")return{type:"tab",title:"Guitar Tab",html:`<div class="tab-block"><pre>e|-----------------------------|\nB|-----------------------------|\nG|-----------------------------|\nD|-----------------------------|\nA|-----------------------------|\nE|-----------------------------|</pre></div>`,style:{fontFamily:"Consolas",color:"#f4c430"}};return{type:"lyrics",title:"VERSE",html:"<div><b>G</b>                 <b>D</b><br>Enter lyrics and chords here...</div>",style:{fontFamily:"Verdana",color:"white"}};}
  function render(){const root=$("sectionEditorList");root.innerHTML="";sections.forEach((s,i)=>{const box=document.createElement("article");box.className="creator-section-card";box.draggable=true;box.dataset.index=i;if(s.type==="separator"){box.innerHTML=`<div class="creator-section-head"><span class="drag">☰</span><strong>SEPARATOR</strong><button data-remove="${i}">×</button></div><hr>`;}else if(s.type==="performanceNote"){box.innerHTML=`<div class="creator-section-head"><span class="drag">☰</span><input data-title="${i}" value="${esc(s.title||'Performance Note')}"><div><button data-up="${i}">↑</button><button data-down="${i}">↓</button><button data-remove="${i}">×</button></div></div><textarea class="performance-note-editor" data-note="${i}">${esc(s.text||"")}</textarea>`;}else{box.innerHTML=`<div class="creator-section-head"><span class="drag">☰</span><input data-title="${i}" value="${esc(s.title||'')}"><span class="section-type-badge">${s.type==='tab'?'TAB':'LYRICS'}</span><div><button data-up="${i}">↑</button><button data-down="${i}">↓</button><button data-remove="${i}">×</button></div></div><div class="rich-toolbar"><button type="button" data-command="bold">B</button><button type="button" data-command="italic"><i>I</i></button><button type="button" data-command="underline"><u>U</u></button><button type="button" data-insert-chord="${i}">Insert Chord</button></div><div class="creator-rich-editor ${s.type==='tab'?'tab-editor':''}" data-html="${i}" contenteditable="true">${s.html||""}</div>`;}root.appendChild(box);});enableDrag();}
  function sync(){document.querySelectorAll("[data-title]").forEach(el=>sections[+el.dataset.title].title=el.value);document.querySelectorAll("[data-note]").forEach(el=>sections[+el.dataset.note].text=el.value);document.querySelectorAll("[data-html]").forEach(el=>sections[+el.dataset.html].html=el.innerHTML);}
  async function load(){if(!firebaseId){sections=[makeSection("lyrics")];render();return;}const doc=await db.collection("lyrics").doc(firebaseId).get();if(!doc.exists)return alert("Song not found");loadedSong=doc.data();sections=Array.isArray(loadedSong.sections)?JSON.parse(JSON.stringify(loadedSong.sections)):[];$("creatorHeading").textContent="✎ EDIT LYRICS & CHORDS";$("songTitleInput").value=loadedSong.title||"";$("artistInput").value=loadedSong.artist||"";$("userBpmInput").value=loadedSong.userBpm||"";$("originalBpmInput").value=loadedSong.originalBpm||"";$("keyInput").value=loadedSong.key||"";$("capoInput").value=loadedSong.capo||"";$("yearInput").value=loadedSong.year||"";$("timeSignatureInput").value=loadedSong.timeSignature||"4/4";$("youtubeInput").value=loadedSong.youtubeLink||"";$("hostNoteInput").value=loadedSong.note||"";$("publicVisibleInput").checked=loadedSong.publicSongListVisible===true;render();}
  async function save(){sync();const title=$("songTitleInput").value.trim(),artist=$("artistInput").value.trim();if(!title||!artist)return alert("Title and artist are required.");const id=firebaseId||`${title}${artist}`.toLowerCase().replace(/[^a-z0-9]/g,"");const data={title,artist,userBpm:$("userBpmInput").value,originalBpm:$("originalBpmInput").value,key:$("keyInput").value.trim(),capo:$("capoInput").value.trim(),year:$("yearInput").value,timeSignature:$("timeSignatureInput").value.trim()||"4/4",youtubeLink:$("youtubeInput").value.trim(),note:$("hostNoteInput").value,sections,publicSongListVisible:$("publicVisibleInput").checked,updatedAt:firebase.firestore.FieldValue.serverTimestamp()};if(!firebaseId)data.createdAt=firebase.firestore.FieldValue.serverTimestamp();await db.collection("lyrics").doc(id).set(data,{merge:false});alert(firebaseId?"Song updated.":"Song created and hidden from the Public Song List unless you ticked Show.");location.href=`lyricview.html?id=${encodeURIComponent(id)}`;}
  function enableDrag(){let drag=null;document.querySelectorAll(".creator-section-card").forEach(card=>{card.addEventListener("dragstart",()=>{sync();drag=card;card.classList.add("dragging")});card.addEventListener("dragend",()=>{card.classList.remove("dragging");sections=[...document.querySelectorAll(".creator-section-card")].map(c=>sections[+c.dataset.index]);drag=null;render()});card.addEventListener("dragover",e=>{e.preventDefault();if(!drag||drag===card)return;const r=card.getBoundingClientRect();(e.clientY>r.top+r.height/2?card.after(drag):card.before(drag));});});}
  document.addEventListener("input",e=>{if(e.target.matches("[data-title],[data-note],[data-html]"))sync();});
  document.addEventListener("click",e=>{const rem=e.target.closest("[data-remove]");if(rem){sync();sections.splice(+rem.dataset.remove,1);render();return;}const up=e.target.closest("[data-up]");const down=e.target.closest("[data-down]");const mover=up||down;if(mover){sync();const i=+(mover.dataset.up??mover.dataset.down),j=i+(up?-1:1);if(j>=0&&j<sections.length)[sections[i],sections[j]]=[sections[j],sections[i]];render();return;}const cmd=e.target.closest("[data-command]");if(cmd){document.execCommand(cmd.dataset.command,false,null);return;}const chord=e.target.closest("[data-insert-chord]");if(chord){const value=prompt("Chord (for example G, Am7, F#):","G");if(value)document.execCommand("insertHTML",false,`<b>${esc(value)}</b>`);}});
  $("addLyricsSectionBtn").onclick=()=>{sync();sections.push(makeSection("lyrics"));render()};$("addTabSectionBtn").onclick=()=>{sync();sections.push(makeSection("tab"));render()};$("addPerformanceNoteBtn").onclick=()=>{sync();sections.push(makeSection("performanceNote"));render()};$("addSeparatorBtn").onclick=()=>{sync();sections.push(makeSection("separator"));render()};$("saveSongBtn").onclick=save;load();
})();
