(() => {
class Timestamp{constructor(ms){this.ms=ms;}toDate(){return new Date(this.ms);}toMillis(){return this.ms;}static fromMillis(ms){return new Timestamp(ms);}static fromDate(d){return new Timestamp(+d);}static now(){return new Timestamp(Date.now());}}
const t=s=>Timestamp.fromDate(new Date(s));
const songs=['Lanterns on the Quay','Harbour Lights','Paper Satellites','Morning Ferry'].map((title,i)=>({title,artist:'Demo Original',key:'Am',userBpm:96,originalBpm:96,capo:2,year:2026,timeSignature:'4/4',sections:[{type:'verse',title:'VERSE 1',html:'<p><span class="chord">Am</span></p><p>Copper lanterns warm the quay</p><p>Paper boats drift out to sea</p><p>I count the windows turning gold</p><p>And fold the map along the road</p>'},{type:'verse',title:'VERSE 2',html:'<p>F</p><p>Morning paints the harbour wall</p><p>A silver ferry carries all</p>'},{type:'chorus',title:'CHORUS',html:'<p>C</p><p>Carry the lantern home with me</p>'.repeat(10)}]}));
const data={'karaoke/state':{isLive:true,songsEnabled:true},'karaokeControl/currentSession':{active:true,sessionId:'s1'},'performanceSessions/s1':{venue:'Black Gold Saloon',location:'Sliema',status:'active',type:'Solo',startedAt:t('2026-09-10T20:05:00'),scheduledStartAt:t('2026-09-10T20:00:00'),scheduledEndAt:t('2026-09-10T23:00:00'),breaks:[],notes:''},'karaokeControl/publicSongList':{setlistId:'set1',setlistName:'Tonight'},'lyricsSetlists/set1':{name:'Tonight',songIds:['song0','song1']},'karaokeControl/runOrder':{sessionId:'s1',items:songs.map((s,i)=>({id:'q'+i,songId:'song'+i,songTitle:s.title,artist:s.artist,status:i===0?'playing':'queued',singerName:i?'Sarah':'',source:'manual'}))}};
songs.forEach((s,i)=>data['lyrics/song'+i]=s);for(let i=0;i<6;i++)data['publicSongRequests/r'+i]={sessionId:'s1',songId:'song1',songTitle:'Harbour Lights '+i,songArtist:'Demo Original',singerName:'Emma',status:'pending',location:'Sliema',note:'Lower key please'};
window.__fixture={data,calls:[],listeners:[]};
const listeners=[];const snap=(path)=>({id:path.split('/').at(-1),exists:!!data[path],data:()=>data[path],metadata:{fromCache:false}});
function emit(){for(const l of listeners)l.cb(l.ref.snapshot());}
class Ref{constructor(path,filters=[]){this.path=path;this.filters=filters;this.id=path.split('/').at(-1);}doc(id){return new Ref(this.path+'/'+(id||crypto.randomUUID()));}collection(name){return new Ref(this.path+'/'+name);}where(...args){return new Ref(this.path,[...this.filters,args]);}orderBy(){return this;}limit(){return this;}startAfter(){return this;}snapshot(){if(this.path.split('/').length%2===0)return snap(this.path);const docs=Object.keys(data).filter(k=>k.startsWith(this.path+'/')&&k.split('/').length===this.path.split('/').length+1).filter(k=>this.filters.every(([f,op,v])=>op==='=='?data[k][f]===v:true)).map(snap);return {docs,size:docs.length,empty:!docs.length,forEach:f=>docs.forEach(f),docChanges:()=>docs.map(doc=>({doc,type:'added'})),metadata:{fromCache:false}};}async get(){__fixture.calls.push(['get',this.path]);return this.snapshot();}onSnapshot(...args){const cb=args.find(x=>typeof x==='function');const l={ref:this,cb};listeners.push(l);__fixture.listeners.push(this.path);queueMicrotask(()=>cb(this.snapshot()));return()=>{const i=listeners.indexOf(l);if(i>=0)listeners.splice(i,1);};}async set(v,opts){__fixture.calls.push(['set',this.path]);data[this.path]=opts?.merge?{...data[this.path],...v}:v;queueMicrotask(emit);}update(v){return this.set(v,{merge:true});}async add(v){const r=this.doc();await r.set(v);return r;}async delete(){delete data[this.path];}}
const db={collection:p=>new Ref(p),doc:p=>new Ref(p),enablePersistence:async()=>{},runTransaction:async cb=>{const writes=[];const tx={get:r=>r.get(),set:(...args)=>writes.push(['set',...args]),update:(...args)=>writes.push(['update',...args])};const result=await cb(tx);for(const [method,r,...args]of writes)await r[method](...args);return result;},batch:()=>{const writes=[];return {set:(...a)=>writes.push(['set',...a]),update:(...a)=>writes.push(['update',...a]),commit:async()=>{for(const [m,r,...a]of writes)await r[m](...a);}}}};
const auth={currentUser:{uid:'test-host',email:'host@example.test'},onAuthStateChanged:cb=>{queueMicrotask(()=>cb(auth.currentUser));return()=>{};},signOut:async()=>{},signInWithEmailAndPassword:async()=>{}};
const firestore=()=>db;Object.assign(firestore,{Timestamp,FieldValue:{serverTimestamp:()=>Timestamp.now(),arrayUnion:(...a)=>a},DocumentReference:Ref,Query:Ref});window.firebase={apps:[],initializeApp:config=>{firebase.apps.push({options:config});},app:()=>firebase.apps[0],firestore,auth:()=>auth};
})();
