/* Copyright © 2026 LiveSuite. Local timer/section regression checks; no live Firebase. */
const vm=require('vm'),fs=require('fs'),path=require('path'),assert=require('assert');
const els=new Map();function el(id){if(!els.has(id)){let value='';const classes=new Set();els.set(id,{writes:0,get textContent(){return value},set textContent(v){value=String(v);this.writes++},innerHTML:'',classList:{remove(...v){v.forEach(x=>classes.delete(x))},toggle(k,on){on?classes.add(k):classes.delete(k)},contains:k=>classes.has(k)}})}return els.get(id)}
let now=Date.parse('2026-09-10T21:00:00Z');class Clock extends Date{static now(){return now}}
const ctx={console,Date:Clock,Map,Set,Promise,localStorage:{getItem:()=>null,setItem(){}},sessionStorage:{getItem:()=>null,setItem(){}},document:{readyState:'loading',getElementById:el,addEventListener(){}},window:null};ctx.window=ctx;ctx.addEventListener=()=>{};ctx.dispatchEvent=()=>{};vm.createContext(ctx);
let code=fs.readFileSync(path.join(__dirname,'../admin-new/js/top-statusbar-session-tools.js'),'utf8').replace('  const $ = id => document.getElementById(id);','  window.test={state,tick:()=>{renderCompactHostStrip();renderRemaining();}};\n  const $ = id => document.getElementById(id);');vm.runInContext(code,ctx);
ctx.test.state.db=new Proxy({},{get(){throw Error('Unexpected database access during local timer')}});Object.assign(ctx.test.state,{sessionId:'s',session:{venue:'Test Venue',startedAt:new Clock('2026-09-10T20:05:00Z'),scheduledStartAt:new Clock('2026-09-10T20:00:00Z'),scheduledEndAt:new Clock('2026-09-10T23:00:00Z'),scheduledDurationMs:10800000}});
ctx.test.tick();const count=el('tsCompactType').writes;for(let i=0;i<120;i++){now+=1000;ctx.test.tick()}assert.equal(el('tsCompactType').writes,count);assert.equal(el('tsCompactVenue').writes,1);assert.equal(el('tsCompactScheduledEnd').textContent,'+5mins late');
now=Date.parse('2026-09-10T23:09:59Z');ctx.test.tick();assert.equal(el('tsCompactRemaining').classList.contains('is-overdue'),false);now+=1000;ctx.test.tick();assert.equal(el('tsCompactRemaining').classList.contains('is-overdue'),true);assert.equal(el('tsCompactRemaining').textContent,'−5m');
console.log('PASS: stable labels for 120 local ticks, no database access, late-start label and exact minus-five-minute threshold.');
let source=fs.readFileSync(path.join(__dirname,'../host/js/lyricview.js'),'utf8');source=source.slice(source.indexOf('  function scrollToSection(index)'),source.indexOf('  window.addEventListener("resize"',source.indexOf('  function scrollToSection(index)')));
const nav={console,Date:Clock,currentSectionIndex:0,manualSectionUntil:0,relativeScrollFrame:0,setTimeout(){},cancelAnimationFrame(){},centerActiveProgressSection(){},document:{getElementById:id=>id==='ls26StickyHeader'?{getBoundingClientRect:()=>({height:150})}:id==='performanceQuickInfo'?{classList:{toggle(){},contains:()=>true},getBoundingClientRect:()=>({height:60})}:null},$:()=>({children:[]}),window:{scrollY:0,scrollTo({top}){this.scrollY=top}}};nav.sectionEls=[200,500,1100].map(top=>({getBoundingClientRect:()=>({top:top-nav.window.scrollY}),classList:{toggle(){}}}));vm.createContext(nav);vm.runInContext(source,nav);now=0;nav.scrollToSection(1);nav.updateSectionProgress();assert.equal(nav.currentSectionIndex,1);nav.scrollToSection(nav.currentSectionIndex+1);assert.equal(nav.currentSectionIndex,2);now=1000;nav.updateSectionProgress();assert.equal(nav.currentSectionIndex,2);assert.equal(nav.window.scrollY,938);
console.log('PASS: consecutive Next Section commands retain their destination through progress tracking.');
